import * as React from "react"

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel="preload"
      href="./fonts/Alegreya-Medium.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="AlegreyaMedium"
    />,
    <link
      rel="preload"
      href="./fonts/Alegreya-MediumItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="AlegreyaMediumItalic"
    />,
    <link
      rel="preload"
      href="./fonts/Alegreya-ExtraBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="AlegreyaBold"
    />,
    <link
      rel="preload"
      href="./fonts/Alegreya-ExtraBoldItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="AlegreyaBoldItalic"
    />,
    <link
      rel="preload"
      href="./fonts/ExocetHeavy.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="ExocetHeavy"
    />,
    <link
      rel="preload"
      href="./fonts/BlackmoorLET.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="Blackmoor"
    />,
  ])
}