const characterOracleResults = {
    "oracle-character-role-result": [
        "Adventurer",
        "Artisan",
        "Bandit",
        "Criminal",
        "Farmer",
        "Fisher",
        "Forager",
        "Forester",
        "Guard",
        "Guide",
        "Healer",
        "Herder",
        "Hunter",
        "Leader",
        "Mercenary",
        "Miner",
        "Mystic",
        "Outcast",
        "Performer",
        "Pilgrim",
        "Priest",
        "Raider",
        "Sailor",
        "Scout",
        "Thief",
        "Trader",
        "Traveler",
        "Vagrant",
        "Warrior",
    ],
    "oracle-character-descriptor-result": [
        "Active",
        "Adventurous",
        "Affectionate",
        "Aggressive",
        "Agreeable",
        "Aloof",
        "Ambitious",
        "Angry",
        "Anxious",
        "Apathetic",
        "Armed",
        "Armored",
        "Artistic",
        "Athletic",
        "Attractive",
        "Bitter",
        "Bold",
        "Brave",
        "Careless",
        "Cautious",
        "Charming",
        "Cheery",
        "Clever",
        "Conceited",
        "Confident",
        "Confused",
        "Connected",
        "Cooperative",
        "Cowardly",
        "Critical",
        "Cruel",
        "Cunning",
        "Dangerous",
        "Deceitful",
        "Dependent",
        "Determined",
        "Disabled",
        "Disfigured",
        "Doomed",
        "Driven",
        "Dying",
        "Experienced",
        "Fervent",
        "Friendly",
        "Generous",
        "Greedy",
        "Hardhearted",
        "Honest",
        "Hostile",
        "Hot-tempered",
        "Incompetent",
        "Infamous",
        "Influential",
        "Insensitive",
        "Insightful",
        "Intolerant",
        "Jealous",
        "Kind",
        "Loyal",
        "Manipulative",
        "Oblivious",
        "Obsessed",
        "Old",
        "Oppressed",
        "Passive",
        "Powerful",
        "Proud",
        "Quiet",
        "Quirky",
        "Reclusive",
        "Relaxed",
        "Religious",
        "Remorseful",
        "Resourceful",
        "Selfish",
        "Sick",
        "Skilled",
        "Smug",
        "Sociable",
        "Stealthy",
        "Stern",
        "Stingy",
        "Stoic",
        "Strong",
        "Stubborn",
        "Successful",
        "Suspicious",
        "Talented",
        "Timid",
        "Ugly",
        "Vengeful",
        "Violent",
        "Wary",
        "Weak",
        "Weary",
        "Wild",
        "Wise",
        "Wounded",
        "Young",
    ],
    "oracle-character-goal-result": [
        "Advance status",
        "Avenge a wrong",
        "Build a relationship",
        "Collect a debt",
        "Create an item",
        "Cure an ill",
        "Defend a place",
        "Enrich themselves",
        "Escape from something",
        "Find a home",
        "Find a person",
        "Find redemption",
        "Fulfill a duty",
        "Gain knowledge",
        "Harm a rival",
        "Make an agreement",
        "Obtain an object",
        "Pay a debt",
        "Protect a person",
        "Protect a secret",
        "Protect the status quo",
        "Prove worthiness",
        "Rebel against power",
        "Refute a falsehood",
        "Resolve a dispute",
        "Restore a relationship",
        "Secure provisions",
        "Seek a truth",
        "Seize power",
        "Spread faith",
        "Travel to a place",
        "Undermine a relationship",
    ],
    "oracle-character-traits-result": [
        "Always bored",
        "Angry drunk",
        "Annoyingly Cryptic",
        "Avant-garde",
        "Bigoted",
        "Bloody-Minded",
        "Boastful",
        "Bookworm",
        "Bossy",
        "Bully",
        "Calculating",
        "Can-do attitude",
        "Chatterbox",
        "Chirpy",
        "Collects small animals",
        "Compulsive Liar",
        "Condescending",
        "Conniving",
        "Conspiracy theorist",
        "Creep",
        "Decadent",
        "Ditz",
        "Egomaniac",
        "Exquisite dresser",
        "Extravagant",
        "Fanatically loyal",
        "Fast-talker",
        "Fiercely ambitious",
        "Fits of melancholy",
        "Flamboyant",
        "Folksy Wisdom",
        "Gossip",
        "Hard-boiled",
        "Hears voices",
        "Hillbilly",
        "Hothead",
        "Hypochondriac",
        "Iconoclast",
        "Idealistic",
        "Illiterate",
        "Incredibly persistent",
        "Insightful observer",
        "Into crystals",
        "Jack of all Trades",
        "Jerk",
        "Klutz",
        "Knows everybody",
        "Life of the party",
        "Love-struck",
        "Mad genius",
        "Magnetic Personality",
        "Manic",
        "Master Orator",
        "Militantly Vegan",
        "Misanthrope",
        "Miser",
        "Mopey",
        "Naïve",
        "Nerd",
        "No-nonsense",
        "Obsessive",
        "Old Fart",
        "Overeducated",
        "Paranoid",
        "Perfect Manners",
        "Pouty",
        "Power-hungry",
        "Prickly",
        "Proselytizer",
        "Ruthless",
        "Sadist",
        "Self-destructive",
        "Self-important",
        "Self-pitying",
        "Senile",
        "Serene",
        "Shameless Flirt",
        "Slacker",
        "Slimy",
        "Slovenly",
        "Snarky",
        "Snitch",
        "Snob",
        "Social butterfly",
        "Sophist",
        "Spacey",
        "Terrible memory",
        "Thick",
        "Toady",
        "Totally unreliable",
        "Twitchy",
        "Vain",
        "Vengeful",
        "Village idiot",
        "Well-Travelled",
        "Whiner",
        "Wild Child",
        "Wisecracking",
        "World-weary",
    ],
    "oracle-character-mannerisms-result": [
        "Speaks at very different rates",
        "Speaks in a sing-song up and down pitch",
        "Speaks in whispers",
        "Speaks of self in the third person",
        "Speaks of the good ol’ days",
        "Speaks too loudly",
        "Speaks too quickly",
        "Speaks too quietly",
        "Speaks very slowly",
        "Spits in hand before shaking hands",
        "Spits when speaking",
        "Squints",
        "Suffers from dementia",
        "Sweats profusely",
        "Talks with a lisp",
        "Tells jokes but forgets the punch lines",
        "Thinks very hard about answers before responding.",
        "Trying not to giggle",
        "Usually stands straight then crouches when lying.",
        "Whispering Echolalia",
        "Will often pause mid sentence",
        "Winks frequently",
    ],
    "oracle-character-ethnicity-result": [
        "<a href=\"/oracles/character-oracles#character-arabic\">Arabic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-celtic\">Celtic</a>",
        "<a href=\"/oracles/character-oracles#character-chinese\">Chinese</a>",
        "<a href=\"/oracles/character-oracles#character-egyptian\">Egyptian</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-english\">English</a>",
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-french\">French</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-german\">German</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-greek\">Greek</a>", 
        "<a href=\"/oracles/character-oracles#character-indian\">Indian</a>",
        "<a href=\"/oracles/character-oracles#character-mesoamerican\">Mesoamerican</a>",
        "<a href=\"/oracles/character-oracles#character-nigercongo\">Niger-Congo</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-norse\">Norse</a>",
        "<a href=\"/oracles/character-oracles#character-polynesian\">Polynesian</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-roman\">Roman</a>",
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-slavic\">Slavic</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
        "<a href=\"/oracles/character-oracles#character-spanish\">Spanish</a>", 
    ],
    "oracle-character-caste-result": [
        "Crafter",
        "Escaped Serf/Slave",
        "Farmer",
        "Herder",
        "Merchant",
        "Outcast",
        "Petty Nobility",
        "Priesthood",
        "Warrior",
        "Raider",
    ],
    "oracle-character-education-result": [
        "Against Their Parents’ Will",
        "Apprenticed Abroad",
        "Educated on the Battlefield",
        "Elder Mentor",
        "Family Footsteps",
        "From Masterful Tutors",
        "Largely Absent",
        "Their Own Terms",
        "Traditional",
        "Under Duress",
    ],
    "oracle-character-war-story-result": [
        "Defeated a Savage Beast",
        "Dispossessed",
        "Gained (and Lost) a Great Treasure",
        "Gained the Favor of a Local Lord",
        "Prevented a Disaster",
        "Shipwrecked",
        "Survived a Duel",
        "Survived a Massacre",
        "Survived a Stint at Court",
        "Survived Witchcraft",
    ],
    "oracle-character-disposition-result": [
        "Cooperative",
        "Curious",
        "Demanding",
        "Desperate",
        "Friendly",
        "Helpful",
        "Hostile",
        "Indifferent",
        "Suspicious",
        "Threatening",
        "Unfriendly",
        "Wanting",
    ],
    "oracle-character-activity-result": [
        "Ambushing",
        "Assaulting",
        "Assisting",
        "Avoiding",
        "Bargaining",
        "Constructing",
        "Consuming",
        "Controlling",
        "Creating",
        "Defending",
        "Destroying",
        "Disabling",
        "Distracting",
        "Ensnaring",
        "Escorting",
        "Exploring",
        "Fighting",
        "Fleeing",
        "Gathering",
        "Guarding",
        "Hiding",
        "Hunting",
        "Inspecting",
        "Journeying",
        "Leading",
        "Learning",
        "Leaving",
        "Luring",
        "Mending",
        "Mimicking",
        "Observing",
        "Patrolling",
        "Preserving",
        "Raiding",
        "Recovering",
        "Removing",
        "Resting",
        "Restoring",
        "Sacrificing",
        "Searching",
        "Securing",
        "Seizing",
        "Sneaking",
        "Socializing",
        "Suffering",
        "Summoning",
        "Supporting",
        "Threatening",
        "Tracking",
        "Tricking",
    ],
    "oracle-character-faeborn-male-result": [
        "Aborn",
        "Alenor",
        "Aloduvardel",
        "Alon",
        "Alorond",
        "Anor",
        "Arenor",
        "Areshelas",
        "Arond",
        "Avalon",
        "Cedel",
        "Ceduvar",
        "Celalas",
        "Celas",
        "Celoel",
        "Cemarvar",
        "Cerelil",
        "Cerobrin",
        "Ceroil",
        "Corond",
        "Covar",
        "Ebrin",
        "Egonor",
        "Elbalfane",
        "Eledavar",
        "Eledulas",
        "Elelodir",
        "Elelon",
        "Elerelas",
        "Eleroborn",
        "Elerond",
        "Elevan",
        "Elevarond",
        "Elfinel",
        "Elladel",
        "Ellalodel",
        "Ellavar",
        "Ellevan",
        "Elolon",
        "Elrebin",
        "Elrolon",
        "Elronor",
        "Elysirond",
        "Erond",
        "Fendel",
        "Fenlafane",
        "Fenlenor",
        "Fennor",
        "Fenrel",
        "Ifanelas",
        "Ilas",
        "Iledel",
        "Ilodellon",
        "Irelfane",
        "Irond",
        "Irovar",
        "Ivaril",
        "Ivarnor",
        "Ivarrond",
        "Laloborn",
        "Larebrin",
        "Lebelon",
        "Lebin",
        "Lefanerash",
        "Lelas",
        "Lelolas",
        "Lemaril",
        "Lenor",
        "Lerebrin",
        "Lerobin",
        "Levar",
        "Obaldel",
        "Obin",
        "Ogovar",
        "Olaborn",
        "Olofane",
        "Orashdel",
        "Ovarrelon",
        "Redel",
        "Relavar",
        "Relevar",
        "Relevar",
        "Reredel",
        "Sael",
        "Salobrin",
        "Saredel",
        "Sarelas",
        "Sarond",
        "Savael",
        "Shelevan",
        "Shelon",
        "Sherolas",
        "Thrandelel",
        "Thranel",
        "Thranloel",
        "Thranrolon",
        "Thranvarnor",
        "Ubenor",
        "Ulelon",
        "Ulovan",
    ],
    "oracle-character-faeborn-female-result": [
        "Aea",
        "Alanlia",
        "Alansineth",
        "Alansirynna",
        "Aldarynna",
        "Aldrilee",
        "Alea",
        "Aleaneth",
        "Allannia",
        "Allialynn",
        "Alliarynna",
        "Alrynna",
        "Alsiea",
        "Aneth",
        "Ania",
        "Belaneania",
        "Bethdalee",
        "Bethdalelynn",
        "Bethelee",
        "Bethlee",
        "Bethlynn",
        "Bethnia",
        "Caedaneth",
        "Caedarynna",
        "Caedrydaneth",
        "Caelanrynna",
        "Caelelynn",
        "Caelynn",
        "Caenia",
        "Caerynna",
        "Canea",
        "Drudarynna",
        "Drulanneth",
        "Drulee",
        "Drulesilia",
        "Drulia",
        "Drunea",
        "Druneth",
        "Drunia",
        "Drusidarynna",
        "Druthaneth",
        "Faedalynn",
        "Hadrilynn",
        "Jaedrileneth",
        "Jedalia",
        "Jedrinia",
        "Jeea",
        "Jelanea",
        "Jelannia",
        "Jelelia",
        "Jelelynn",
        "Jeleneth",
        "Jeliaea",
        "Jelialia",
        "Jeliania",
        "Jeliasea",
        "Jenia",
        "Jerynna",
        "Jesilia",
        "Jethalynn",
        "Lurynna",
        "Lusilia",
        "Miadalea",
        "Miadalee",
        "Miadalia",
        "Miadriea",
        "Miadrilia",
        "Miadrinia",
        "Miadyfae",
        "Miaea",
        "Mialanlee",
        "Mialanneth",
        "Mialanrynna",
        "Mialee",
        "Miania",
        "Miathadalynn",
        "Miresiea",
        "Nealedrilia",
        "Nialynn",
        "Shaelanea",
        "Shiadridania",
        "Vadalee",
        "Vadasinia",
        "Vadriea",
        "Vaealee",
        "Vaeania",
        "Valanlee",
        "Valanlia",
        "Valannia",
        "Valansiea",
        "Valeneth",
        "Valerynna",
        "Valia",
        "Valialee",
        "Valiarynna",
        "Vandalynn",
        "Vaneth",
        "Varynna",
        "Vasineth",
        "Vathaneth",
    ],
    "oracle-character-faeborn-clan-result": [
        "Allleaves",
        "Arrowdeep",
        "Arrowmoon",
        "Arrowstrider",
        "Bladeblood",
        "Bladedeep",
        "Bladetail",
        "Bloodbright",
        "Blooddeep",
        "Bloodrune",
        "Bloodtree",
        "Bloodwood",
        "Brightlake",
        "Brightred",
        "Brighttail",
        "Brightwood",
        "Darkarrow",
        "Darkblade",
        "Darkleaves",
        "Dawnarrow",
        "Dawnblade",
        "Dawnfey",
        "Dawnglade",
        "Dawnrune",
        "Dawntail",
        "Dawnwild",
        "Deepglade",
        "Deepleaf",
        "Everblade",
        "Everblood",
        "Everdeep",
        "Everlake",
        "Everleaf",
        "Evermore",
        "Evershine",
        "Feydark",
        "Feyoak",
        "Fountainbright",
        "Fountainmoon",
        "Fountainoak",
        "Fountainrune",
        "Fountainstrider",
        "Gladedeep",
        "Gladefountain",
        "Gladelake",
        "Gladestar",
        "Golddark",
        "Goldfountain",
        "Goldlake",
        "Goldtree",
        "Lakearrow",
        "Lakestar",
        "Leafsparrow",
        "Leafstrider",
        "Leafwild",
        "Leavesglade",
        "Lushfountain",
        "Lushgold",
        "Moonblade",
        "Moondeep",
        "Moonfountain",
        "Moonlush",
        "Moonstrider",
        "Moonwild",
        "Oakfey",
        "Oakgold",
        "Oakmoon",
        "Oldarrow",
        "Oldblade",
        "Oldlake",
        "Oldleaves",
        "Oldlush",
        "Redglade",
        "Redmoon",
        "Runeblade",
        "Runedark",
        "Runelush",
        "Runemoon",
        "Runeoak",
        "Sparrowblood",
        "Sparrowlake",
        "Sparrowleaves",
        "Sparrowstrider",
        "Sparrowtail",
        "Stardark",
        "Starfey",
        "Starglade",
        "Stargold",
        "Starlake",
        "Starstrider",
        "Striderdeep",
        "Stridersparrow",
        "Tailleaves",
        "Tailtree",
        "Treebright",
        "Treefountain",
        "Wildleaves",
        "Wildoak",
        "Wildtail",
        "Woodfountain",
    ],
    "oracle-character-arabic-male-result": [
        "Abbad",
        "Abdul",
        "Achmed",
        "Akeem",
        "Alif",
        "Amir",
        "Asim",
        "Bashir",
        "Bassam",
        "Fahim",
        "Farid",
        "Farouk",
        "Fayez",
        "Fayyaad",
        "Fazil",
        "Hakim",
        "Halil",
        "Hamid",
        "Hazim",
        "Heydar",
        "Hussein",
        "jabari",
        "Jafar",
        "Jahid",
        "Jamal",
        "Kalim",
        "Karim",
        "Kazim",
        "Khadim",
        "Khalid",
        "Mahmud",
        "Mansour",
        "Musharraf",
        "Mustafa",
        "Nadir",
        "Nazim",
        "Omar",
        "Qadir",
        "Qusay",
        "Rafiq",
        "Rakim",
        "Rashad",
        "Rauf",
        "Saladin",
        "Sami",
        "Samir",
        "Talib",
        "Tamir",
        "Tariq",
        "Yazid",
    ],
    "oracle-character-arabic-female-result": [
        "Aaliyah",
        "Aida",
        "Akilah",
        "Alia",
        "Amina",
        "Atefeh",
        "Camila",
        "Chaima",
        "Dalia",
        "Ehsan",
        "Elham",
        "Farah",
        "Fatemah",
        "Iesha",
        "Kamaria",
        "Khadija",
        "Layla",
        "lnbar",
        "Lupe",
        "Nabila",
        "Nadine",
        "Naima",
        "Najila",
        "Najwa",
        "Nakia",
        "Nashwa",
        "Nawra",
        "Nuha",
        "Nura",
        "Oma",
        "Qadira",
        "Qamar",
        "Qistina",
        "Rahima",
        "Rihanna",
        "Saadia",
        "Sabah",
        "Sada",
        "Saffron",
        "Sahar",
        "Salma",
        "Shatha",
        "Tahira",
        "Takisha",
        "Thana",
        "Yadira",
        "Zahra",
        "Zaida",
        "Zaina",
        "Zeinab",
    ],
    "oracle-character-celtic-male-result": [
        "Airell",
        "Airic",
        "Alan",
        "Anghus",
        "Aodh",
        "Bardon",
        "Bearacb",
        "Bevyn",
        "Boden",
        "Bran",
        "Brasil",
        "Bredon",
        "Brian",
        "Bricriu",
        "Bryant",
        "Cadman",
        "Caradoc",
        "Cedric",
        "Conalt",
        "Conbar",
        "Condon",
        "Darcy",
        "Devin",
        "Dillion",
        "Donaghy",
        "Donall",
        "Duer",
        "Eghan",
        "Ewyn",
        "Ferghus",
        "Galvyn",
        "Gildas",
        "Guy",
        "Harvey",
        "Iden",
        "Karney",
        "Kayne",
        "Kelvyn",
        "Kunsgnos",
        "Leigh",
        "lrven",
        "Maccus",
        "Moryn",
        "Neale",
        "Owyn",
        "Pryderi",
        "Reaghan",
        "Taliesin",
        "Tiernay",
        "Turi",
    ],
    "oracle-character-celtic-female-result": [
        "Aife",
        "Aina",
        "Alane",
        "Ardena",
        "Arienh",
        "Beatha",
        "Birgit",
        "Briann",
        "Caomh",
        "Cara",
        "Cinnia",
        "Cordelia",
        "Deheune",
        "Divone",
        "Donia",
        "Doreena",
        "Elsha",
        "Enid",
        "Ethne",
        "Evelina",
        "Fianna",
        "Genevieve",
        "Gilda",
        "Gitta",
        "Grania",
        "Gwyndolin",
        "Isolde",
        "Keelin",
        "Kennocha",
        "Lavena",
        "ldelisa",
        "Lesley",
        "Linnette",
        "Lyonesse",
        "Mabina",
        "Marvina",
        "Mavis",
        "Mirna",
        "Morgan",
        "Muriel",
        "Nareena",
        "Oriana",
        "Regan",
        "Ronat",
        "Rowena",
        "Selma",
        "Ula",
        "Venetia",
        "Wynne",
        "Yseult",
    ],
    "oracle-character-chinese-male-result": [
        "Bingwen",
        "Bo",
        "Bolin",
        "Chang",
        "Chao",
        "Chen",
        "Cheng",
        "Da",
        "Dingxiang",
        "Fang",
        "Feng",
        "Fu",
        "Gang",
        "Guang",
        "Hai",
        "Heng",
        "Hong",
        "Huan",
        "Huang",
        "Huiliang",
        "Huizhong",
        "Jian",
        "Jiayi",
        "Junjie",
        "Kang",
        "Lei",
        "Liang",
        "Ling",
        "Liwei",
        "Meilin",
        "Niu",
        "Peizhi",
        "Peng",
        "Ping",
        "Qiang",
        "Qiu",
        "Quan",
        "Renshu",
        "Rong",
        "Ru",
        "Shan",
        "Shen",
        "Tengfei",
        "Wei",
        "Xiaobo",
        "Xiaoli",
        "Xin",
        "Yang",
        "Ying",
        "Zhong",
    ],
    "oracle-character-chinese-female-result": [
        "Ai",
        "Anming",
        "Baozhai",
        "Bei",
        "Caixia",
        "Changchang",
        "Chen",
        "Chou",
        "Chunhua",
        "Daianna",
        "Daiyu",
        "Die",
        "Ehuang",
        "Fenfang",
        "Ge",
        "Hong",
        "Huan",
        "Huifang",
        "Jia",
        "Jiao",
        "Jiaying",
        "Jingfei",
        "Jinjing",
        "Lan",
        "Li",
        "Lihua",
        "Lin",
        "Ling",
        "Liu",
        "Meili",
        "Ning",
        "Qi",
        "Qiao",
        "Rong",
        "Shu",
        "Shuang",
        "Song",
        "Ting",
        "Wen",
        "Xia",
        "Xiaodan",
        "Xiaoli",
        "Xingjuan",
        "Xue",
        "Ya",
        "Yan",
        "Ying",
        "Yuan",
        "Yue",
        "Yun",
    ],
    "oracle-character-egyptian-male-result": [
        "Ahmose",
        "Akhom",
        "Amasis",
        "Amenemhet",
        "Anen",
        "Banefre",
        "Bek",
        "Djedefre",
        "Djoser",
        "Hekaib",
        "Henenu",
        "Horemheb",
        "Horwedja",
        "Huya",
        "Kagemni",
        "Kawab",
        "Kenamon",
        "Kewap",
        "Khaemwaset",
        "Khafra",
        "Khusebek",
        "lbebi",
        "ldu",
        "lmhotep",
        "lneni",
        "lpuki",
        "lrsu",
        "Masaharta",
        "Meketre",
        "Menkhaf",
        "Merenre",
        "Metjen",
        "Nebamun",
        "Nebetka",
        "Nehi",
        "Nekure",
        "Nessumontu",
        "Pakhom",
        "Pawah",
        "Pawero",
        "Ramose",
        "Rudjek",
        "Sabaf",
        "Sebek-khu",
        "Sebni",
        "Senusret",
        "Shabaka",
        "Somintu",
        "Thaneni",
        "Thethi",
    ],
    "oracle-character-egyptian-female-result": [
        "A’at",
        "Ahset",
        "Amunet",
        "Aneksi",
        "Atet",
        "Baketamon",
        "Betrest",
        "Bunefer",
        "Dedyet",
        "Hatshepsut",
        "Hentie",
        "Herit",
        "Hetepheres",
        "Joba",
        "Kasmut",
        "Kemanub",
        "Khemut",
        "Kiya",
        "lntakaes",
        "lpwet",
        "ltet",
        "Maia",
        "Menhet",
        "Merit",
        "Meritamen",
        "Merneith",
        "Merseger",
        "Muyet",
        "Nebet",
        "Nebetah",
        "Nedjemmut",
        "Nefertiti",
        "Neferu",
        "Neithotep",
        "Nit",
        "Nofret",
        "Nubemiun",
        "Peseshet",
        "Pypuy",
        "Qalhata",
        "Rai",
        "Redji",
        "Sadeh",
        "Sadek",
        "Sitamun",
        "Sitre",
        "Takhat",
        "Tarset",
        "Taweret",
        "Werenro",
    ],
    "oracle-character-english-male-result": [
        "Adam",
        "Adelard",
        "Aldous",
        "Anselm",
        "Arnold",
        "Bernard",
        "Bertram",
        "Charles",
        "Clerebold",
        "Conrad",
        "Diggory",
        "Drogo",
        "Everard",
        "Frederick",
        "Geoffrey",
        "Gerald",
        "Gilbert",
        "Godfrey",
        "Gunter",
        "Guy",
        "Henry",
        "Heward",
        "Hubert",
        "Hugh",
        "Jocelyn",
        "john",
        "Lance",
        "Manfred",
        "Miles",
        "Nicholas",
        "Norman",
        "Odo",
        "Percival",
        "Peter",
        "Ralf",
        "Randal",
        "Raymond",
        "Reynard",
        "Richard",
        "Robert",
        "Roger",
        "Roland",
        "Rolf",
        "Simon",
        "Theobald",
        "Theodoric",
        "Thomas",
        "Timm",
        "William",
        "Wymar",
    ],
    "oracle-character-english-female-result": [
        "Adelaide",
        "Agatha",
        "Agnes",
        "Alice",
        "Aline",
        "Anne",
        "Avelina",
        "Avice",
        "Beatrice",
        "Cecily",
        "Egelina",
        "Eleanor",
        "Elizabeth",
        "Ella",
        "Eloise",
        "Elysande",
        "Emeny",
        "Emma",
        "Emmeline",
        "Ermina",
        "Eva",
        "Galiena",
        "Geva",
        "Giselle",
        "Griselda",
        "Hadwisa",
        "Helen",
        "Herleva",
        "Hugolina",
        "Ida",
        "Isabella",
        "jacoba",
        "Jane",
        "Joan",
        "Juliana",
        "Katherine",
        "Margery",
        "Mary",
        "Matilda",
        "Maynild",
        "Millicent",
        "Oriel",
        "Rohesia",
        "Rosalind",
        "Rosamund",
        "Sarah",
        "Susannah",
        "Sybil",
        "Williamina",
        "Yvonne",
    ],
    "oracle-character-french-male-result": [
        "Ambroys",
        "Ame",
        "Andri",
        "Andriet",
        "Anthoine",
        "Bernard",
        "Charles",
        "Charlot",
        "Colin",
        "Denis",
        "Durant",
        "Edouart",
        "Eremon",
        "Ernault",
        "Ethor",
        "Felix",
        "Floquart",
        "Galleren",
        "Gaultier",
        "Gilles",
        "Guy",
        "Henry",
        "Hugo",
        "Imbert",
        "Jacques",
        "Jacquot",
        "Jean",
        "Jehannin",
        "Louis",
        "Louyson",
        "Loys",
        "Martin",
        "Michel",
        "Mille",
        "Morelet",
        "Nicolas",
        "Nicolle",
        "Oudart",
        "Perrin",
        "Phillippe",
        "Pierre",
        "Regnault",
        "Richart",
        "Robert",
        "Robinet",
        "Sauvage",
        "Simon",
        "Talbot",
        "Tanguy",
        "Vincent",
    ],
    "oracle-character-french-female-result": [
        "Aalis",
        "Agatha",
        "Agnez",
        "Alberea",
        "Alips",
        "Amee",
        "Amelot",
        "Anne",
        "Avelina",
        "Blancha",
        "Cateline",
        "Cecilia",
        "Claricia",
        "Collette",
        "Denisete",
        "Dorian",
        "Edelina",
        "Emelina",
        "Emmelot",
        "Ermentrudis",
        "Gibelina",
        "Gila",
        "Gillette",
        "Guiburgis",
        "Guillemette",
        "Guoite",
        "Hecelina",
        "Heloysis",
        "Helyoudis",
        "Hodeardis",
        "Jaquette",
        "Jehan",
        "Johanna",
        "Juliote",
        "Katerine",
        "lsabellis",
        "Luciana",
        "Margot",
        "Marguerite",
        "Maria",
        "Marie",
        "Melisende",
        "Odelina",
        "Perrette",
        "Petronilla",
        "Sedilia",
        "Stephana",
        "Sybilla",
        "Ysabeau",
        "Ysabel",
    ],
    "oracle-character-german-male-result": [
        "Albrecht",
        "Allexander",
        "Baltasar",
        "Benedick",
        "Berhart",
        "Caspar",
        "Clas",
        "Cristin",
        "Cristoff",
        "Dieterich",
        "Engelhart",
        "Erhart",
        "Felix",
        "Frantz",
        "Fritz",
        "Gerhart",
        "Gotleib",
        "Hans",
        "Hartmann",
        "Heintz",
        "Herman",
        "Jacob",
        "Jeremias",
        "Jorg",
        "Karil",
        "Kilian",
        "Linhart",
        "Lorentz",
        "Ludwig",
        "Marx",
        "Melchor",
        "Mertin",
        "Michel",
        "Moritz",
        "Osswald",
        "Ott",
        "Peter",
        "Rudolff",
        "Ruprecht",
        "Sewastian",
        "Sigmund",
        "Steffan",
        "Symon",
        "Thoman",
        "Ulrich",
        "Vallentin",
        "Wendel",
        "Wilhelm",
        "Wolff",
        "Wolfgang",
    ],
    "oracle-character-german-female-result": [
        "Adelhayt",
        "Affra",
        "Agatha",
        "Allet",
        "Angnes",
        "Anna",
        "Apell",
        "Applonia",
        "Barbara",
        "Brida",
        "Brigita",
        "Cecilia",
        "Clara",
        "Cristina",
        "Dorothea",
        "Duretta",
        "Ella",
        "Els",
        "Elsbeth",
        "Engel",
        "Enlein",
        "Enndlin",
        "Eva",
        "Fela",
        "Fronicka",
        "Genefe",
        "Geras",
        "Gerhauss",
        "Gertrudt",
        "Guttel",
        "Helena",
        "Jonata",
        "Katerina",
        "Kuen",
        "Kungund",
        "lrmel",
        "Lucia",
        "Madalena",
        "Magdalen",
        "Margret",
        "Marlein",
        "Martha",
        "Otilia",
        "Ottilg",
        "Peternella",
        "Reusin",
        "Sibilla",
        "Ursel",
        "Vrsula",
        "Walpurg",
    ],
    "oracle-character-greek-male-result": [
        "Adonis",
        "Adrastos",
        "Aeson",
        "Aias",
        "Aineias",
        "Aiolos",
        "Alekto",
        "Alkeides",
        "Argos",
        "Brontes",
        "Damazo",
        "Dardanos",
        "Deimos",
        "Diomedes",
        "Endymion",
        "Epimetheus",
        "Erebos",
        "Euandros",
        "Ganymedes",
        "Glaukos",
        "Hektor",
        "Heros",
        "Hippolytos",
        "Kadmos",
        "Kastor",
        "Kephalos",
        "Kepheus",
        "Koios",
        "Kreios",
        "lacchus",
        "Laios",
        "lason",
        "Leandros",
        "Linos",
        "Lykos",
        "Melanthios",
        "Menelaus",
        "Mentor",
        "Neoptolemus",
        "Okeanos",
        "Orestes",
        "Pallas",
        "Patroklos",
        "Philandros",
        "Phoibos",
        "Phrixus",
        "Priamos",
        "Pyrrhos",
        "Xanthos",
        "Zephyros",
    ],
    "oracle-character-greek-female-result": [
        "Acantha",
        "Aella",
        "Alektos",
        "Alkippe",
        "Andromeda",
        "Antigone",
        "Ariadne",
        "Astraea",
        "Chloros",
        "Chryseos",
        "Daphne",
        "Despoina",
        "Dione",
        "Eileithyia",
        "Elektra",
        "Euadne",
        "Eudora",
        "Eunomia",
        "Hekabe",
        "Helene",
        "Hermoione",
        "Hippolyte",
        "Ianthe",
        "Iphigenia",
        "Kalliope",
        "Kallisto",
        "Kalypso",
        "Karme",
        "Kassandra",
        "Kassiopeia",
        "Kirke",
        "Kleio",
        "Klotho",
        "Klytie",
        "Kynthia",
        "Leto",
        "lokaste",
        "lole",
        "lsmene",
        "Megaera",
        "Melaina",
        "Melpomene",
        "Nausikaa",
        "Nemesis",
        "Niobe",
        "Ourania",
        "Phaenna",
        "Polymnia",
        "Semele",
        "Theia",
    ],
    "oracle-character-indian-male-result": [
        "Abhay",
        "Ahsan",
        "Ajay",
        "Ajit",
        "Akhil",
        "Amar",
        "Amit",
        "Ananta",
        "Aseem",
        "Ashok",
        "Bahadur",
        "Basu",
        "Chand",
        "Chandra",
        "Damodar",
        "Darhsan",
        "Devdan",
        "Dinesh",
        "Dipak",
        "Gopal",
        "Govind",
        "Harendra",
        "Harsha",
        "Ila",
        "Johar",
        "Kalyan",
        "Kiran",
        "Kumar",
        "Lakshmana",
        "lsha",
        "Mahavir",
        "Narayan",
        "Naveen",
        "Nirav",
        "Prabhakar",
        "Prasanna",
        "Raghu",
        "Rajanikant",
        "Rakesh",
        "Ranjeet",
        "Rishi",
        "Sanjay",
        "Sekar",
        "Shandar",
        "Sumantra",
        "Vijay",
        "Vikram",
        "Vimal",
        "Vishal",
        "Yash",
    ],
    "oracle-character-indian-female-result": [
        "Abha",
        "Aishwarya",
        "Amala",
        "Ananda",
        "Ankita",
        "Archana",
        "Avani",
        "Chandana",
        "Chandrakanta",
        "Chetan",
        "Darshana",
        "Devi",
        "Dipti",
        "Esha",
        "Gauro",
        "Gita",
        "Indira",
        "jaya",
        "Kala",
        "Kalpana",
        "Kamala",
        "Kanta",
        "Kashi",
        "Kishori",
        "Lalita",
        "Lina",
        "lndu",
        "Madhur",
        "Manju",
        "Meera",
        "Mohana",
        "Mukta",
        "Nisha",
        "Nitya",
        "Padma",
        "Pratima",
        "Priya",
        "Rani",
        "Sarala",
        "Shakti",
        "Shanta",
        "Shobha",
        "Sima",
        "Sonal",
        "Sumana",
        "Sunita",
        "Tara",
        "Valli",
        "Vijaya",
        "Vimala",
    ],
    "oracle-character-mesoamerican-male-result": [
        "Achcauhtli",
        "Amoxtli",
        "Chicahua",
        "ChimaIii",
        "Cipactli",
        "Coaxoch",
        "Coyotl",
        "CualIi",
        "Cuauhtemoc",
        "Cuetlachtilo",
        "Cuetzpalli",
        "Cuixtli",
        "Ehecatl",
        "Etalpalli",
        "Huemac",
        "Huitzilihuitl",
        "lccauhtli",
        "llhicamina",
        "ltztli",
        "lxtli",
        "Mahuizoh",
        "Manauia",
        "Matlal",
        "Matlalihuitl",
        "Mazati",
        "Mictlantecuhtli",
        "Milintica",
        "Momoztli",
        "Namacuix",
        "Necalli",
        "Necuametl",
        "Nexahualpilli",
        "Nezahualcoyotl",
        "Nochehuatl",
        "Nopaltzin",
        "Ollin",
        "Quauhtli",
        "Tenoch",
        "Teoxihuitl",
        "Tepiltzin",
        "Tezcacoatl",
        "Tlacaelel",
        "TlaceIel",
        "Tlaloc",
        "Tlanextic",
        "Tlazohtlaloni",
        "Tlazopillo",
        "Uetzcayotl",
        "Xipilli",
        "Yaoti",
    ],
    "oracle-character-mesoamerican-female-result": [
        "Ahuiliztli",
        "Atl",
        "Centehua",
        "Chalchiuitl",
        "Chipahua",
        "Cihuaton",
        "Citlali",
        "Citlalmina",
        "Coszcatl",
        "Cozamalotl",
        "Cuicatl",
        "Eleuia",
        "Eloxochitl",
        "Eztli",
        "lchtaca",
        "lcnoyotl",
        "lhuicatl",
        "llhuitl",
        "ltotia",
        "luitl",
        "lxcatzin",
        "lzel",
        "Malinalxochitl",
        "Mecatl",
        "Meztli",
        "Miyaoaxochitl",
        "Mizquixaual",
        "Moyolehuani",
        "Nahuatl",
        "Necahual",
        "Nenetl",
        "Nochtli",
        "Noxochicoztli",
        "Ohtli",
        "Papan",
        "PatIi",
        "Quetzalxochitl",
        "Sacnite",
        "Teicui",
        "Tepin",
        "Teuicui",
        "Teyacapan",
        "Tiaco",
        "TiaIii",
        "Tlacoehua",
        "Tlacotl",
        "Tlanextli",
        "Xihuitl",
        "Xiuhcoatl",
        "Xiuhtonal",
    ],
    "oracle-character-nigercongo-male-result": [
        "Abebe",
        "Abel",
        "Abidemi",
        "Abrafo",
        "Adisa",
        "Amadi",
        "Amara",
        "Anyim",
        "Azubuike",
        "Bapoto",
        "Baraka",
        "Bohlale",
        "Bongani",
        "Bujune",
        "Buziba",
        "Chakide",
        "Chibuzo",
        "Chika",
        "Chimola",
        "Chiratidzo",
        "Dabulamanzi",
        "Dumisa",
        "Dwanh",
        "Emeka",
        "Folami",
        "Gatura",
        "Gebhuza",
        "Gero",
        "Kagiso",
        "Kamau",
        "Katlego",
        "lsoba",
        "Masego",
        "Matata",
        "Nthanda",
        "Ogechi",
        "Olwenyo",
        "Osumare",
        "Paki",
        "Qinisela",
        "Quanda",
        "Samanya",
        "Shanika",
        "Sibonakal",
        "Tapiwa",
        "Thabo",
        "Themba",
        "Uzoma",
        "Zuberi",
        "Zuri",
    ],
    "oracle-character-nigercongo-female-result": [
        "Abebi",
        "Abena",
        "Abimbola",
        "Akachi",
        "Akoko",
        "Alaba",
        "Anuli",
        "Ayo",
        "Bolanle",
        "Bosede",
        "Chiamaka",
        "Chidi",
        "Chidimma",
        "Chinyere",
        "Chioma",
        "Dada",
        "Ebele",
        "Efemena",
        "Ejiro",
        "Ekundayo",
        "Enitan",
        "Funanya",
        "Kunto",
        "Lesedi",
        "lfunanya",
        "lge",
        "lme",
        "Lumusi",
        "Mojisola",
        "Monifa",
        "Nakato",
        "Ndidi",
        "Ngozi",
        "Nkiruka",
        "Nneka",
        "Ogechi",
        "Olamide",
        "Oluchi",
        "Omolara",
        "Onyeka",
        "Simisola",
        "Temitope",
        "Thema",
        "Titlayo",
        "Udo",
        "Uduak",
        "Ufuoma",
        "Yaa",
        "Yejide",
        "Yewande",
    ],
    "oracle-character-norse-male-result": [
        "Agni",
        "Alaric",
        "Anvindr",
        "Arvid",
        "Asger",
        "Asmund",
        "Bjarte",
        "Bjorg",
        "Bjorn",
        "Brandr",
        "Brandt",
        "Brynjar",
        "Calder",
        "Colborn",
        "Cuyler",
        "Egil",
        "Einar",
        "Eric",
        "Erland",
        "Fiske",
        "Folkvar",
        "Frede",
        "Fritjof",
        "Geir",
        "Halvar",
        "Hemming",
        "Hjalmar",
        "Hjortr",
        "Ivar",
        "Knud",
        "Leif",
        "Liufr",
        "lngimarr",
        "Manning",
        "Oddr",
        "Olin",
        "Ormr",
        "Ove",
        "Rannulfr",
        "Sigurd",
        "Skari",
        "Snorri",
        "Sten",
        "Stigandr",
        "Stigr",
        "Sven",
        "Trygve",
        "Ulf",
        "Vali",
        "Vidar",
    ],
    "oracle-character-norse-female-result": [
        "Alfhild",
        "Arnbjorg",
        "Ase",
        "Aslog",
        "Astrid",
        "Auda",
        "Audhid",
        "Bergljot",
        "Birghild",
        "Bodil",
        "Brenna",
        "Brynhild",
        "Dagmar",
        "Eerika",
        "Eira",
        "Gudrun",
        "Gunborg",
        "Gunhild",
        "Gunvor",
        "Helga",
        "Hertha",
        "Hilde",
        "Hillevi",
        "Ingrid",
        "Iona",
        "Jorunn",
        "Kari",
        "Kenna",
        "Magnhild",
        "Nanna",
        "Olga",
        "Ragna",
        "Ragnhild",
        "Ranveig",
        "Runa",
        "Saga",
        "Sigfrid",
        "Signe",
        "Sigrid",
        "Sigrunn",
        "Solveg",
        "Svanhild",
        "Thora",
        "Torborg",
        "Torunn",
        "Tove",
        "Unn",
        "Vigdis",
        "Ylva",
        "Yngvild",
    ],
    "oracle-character-polynesian-male-result": [
        "Afa",
        "Ahohako",
        "Aisake",
        "Aleki",
        "Anewa",
        "Anitelu",
        "Aputi",
        "Ariki",
        "Butat",
        "Enele",
        "Fef",
        "Fuifui",
        "Ha’aheo",
        "Hanano",
        "Hanohano",
        "Haunui",
        "Hekili",
        "Hiapo",
        "Hikawera",
        "HO’eu",
        "Ho’onani",
        "Hoku",
        "Ina",
        "Ka",
        "Ka’aukai",
        "Ka’eo",
        "Kaelani",
        "Kahale",
        "Kaiea",
        "Kaikoa",
        "Kana’I",
        "Koamalu",
        "Laki",
        "ltu",
        "Makai",
        "Manu",
        "Manuka",
        "Nui",
        "Pono",
        "Popoki",
        "Ruru",
        "Tahu",
        "Taurau",
        "Tuala",
        "Turoa",
        "Tusitala",
        "Uaine",
        "Waata",
        "Waipuna",
        "Zamar",
    ],
    "oracle-character-polynesian-female-result": [
        "Ahulani",
        "Airini",
        "Alani",
        "Aluala",
        "Anahera",
        "Anuhea",
        "Aolani",
        "Elenoa",
        "Emele",
        "Fetia",
        "Fiva",
        "H i’ilei",
        "Halona",
        "Hina",
        "Hinatea",
        "Huali",
        "Isa",
        "Ka ‘ana’ana",
        "Ka’ena",
        "Kaamia",
        "Kahula",
        "Kailani",
        "Kamaile",
        "Kamakani",
        "Kamea",
        "Latai",
        "Liona",
        "lnia",
        "lnina",
        "Lokelani",
        "lolani",
        "Marva",
        "Mehana",
        "Millawa",
        "Moana",
        "Ngana",
        "Nohea",
        "Pelika",
        "Sanoe",
        "Satina",
        "Tahia",
        "Tasi",
        "Tiaho",
        "Tihani",
        "Toroa",
        "Ulanni",
        "Uluwehi",
        "Vaina",
        "Waiola",
        "Waitara",
    ],
    "oracle-character-roman-male-result": [
        "Aelius",
        "Aetius",
        "Agrippa",
        "Albanus",
        "Albus",
        "Antonius",
        "Appius",
        "Aquilinus",
        "Atilus",
        "Augustus",
        "Aurelius",
        "Avitus",
        "Balbus",
        "Blandus",
        "Blasius",
        "Brutus",
        "Caelius",
        "Caius",
        "Casian",
        "Cassius",
        "Cato",
        "Celsus",
        "Claudius",
        "Cloelius",
        "Cnaeus",
        "Crispus",
        "Cyprianus",
        "Diocletianus",
        "Egnatius",
        "Ennius",
        "Fabricius",
        "Faustus",
        "Gaius",
        "Germanus",
        "Gnaeus",
        "Horatius",
        "lovianus",
        "Lucilius",
        "lulius",
        "Manius",
        "Marcus",
        "Marius",
        "Maximus",
        "Octavius",
        "Paulus",
        "Quintilian",
        "Regulus",
        "Servius",
        "Tacitus",
        "Varius",
    ],
    "oracle-character-roman-female-result": [
        "Aelia",
        "Aemilia",
        "Agrippina",
        "Alba",
        "Antonia",
        "Aquila",
        "Augusta",
        "Aurelia",
        "Balbina",
        "Blandina",
        "Caelia",
        "Camilla",
        "Casia",
        "Claudia",
        "Cloelia",
        "Domitia",
        "Drusa",
        "Fabia",
        "Fabricia",
        "Fausta",
        "Flavia",
        "Floriana",
        "Fulvia",
        "Germana",
        "Glaucia",
        "Gratiana",
        "Hadriana",
        "Hermina",
        "Horatia",
        "Hortensia",
        "Laelia",
        "Laurentia",
        "Livia",
        "Longina",
        "lovita",
        "Lucilla",
        "Lucretia",
        "lulia",
        "Marcella",
        "Marcia",
        "Maxima",
        "Nona",
        "Octavia",
        "Paulina",
        "Petronia",
        "Porcia",
        "Tacita",
        "Tullia",
        "Verginia",
        "Vita",
    ],
    "oracle-character-slavic-male-result": [
        "Aleksandru",
        "Berislav",
        "Blazh",
        "Bogumir",
        "Boguslav",
        "Borislav",
        "Bozhidar",
        "Bratomil",
        "Bratoslav",
        "Bronislav",
        "Chedomir",
        "Chestibor",
        "Chestirad",
        "Chestislav",
        "Desilav",
        "Dmitrei",
        "Dobromil",
        "Dobroslav",
        "Dragomir",
        "Dragutin",
        "Drazhan",
        "Gostislav",
        "Kazimir",
        "Kyrilu",
        "Lyubomir",
        "Mechislav",
        "Milivoj",
        "Milosh",
        "Mstislav",
        "Nikola",
        "Ninoslav",
        "Premislav",
        "Radomir",
        "Radovan",
        "Ratimir",
        "Rostislav",
        "Slavomir",
        "Stanislav",
        "Svetoslav",
        "Tomislav",
        "Vasili",
        "Velimir",
        "Vladimir",
        "Vladislav",
        "Vlastimir",
        "Volodimeru",
        "Vratislav",
        "Yarognev",
        "Yaromir",
        "Zbignev",
    ],
    "oracle-character-slavic-female-result": [
        "Agripina",
        "Anastasiya",
        "Bogdana",
        "Boleslava",
        "Bozhena",
        "Danica",
        "Darya",
        "Desislava",
        "Dragos lava",
        "Dunja",
        "Efrosinia",
        "Ekaterina",
        "Elena",
        "Faina",
        "Galina",
        "Irina",
        "Iskra",
        "Jasna",
        "Katarina",
        "Katya",
        "Kresimira",
        "Lyudmila",
        "Magda",
        "Mariya",
        "Militsa",
        "Miloslava",
        "Mira",
        "Miroslava",
        "Mokosh",
        "Morana",
        "Natasha",
        "Nika",
        "Olga",
        "Rada",
        "Radoslava",
        "Raisa",
        "Slavitsa",
        "Sofiya",
        "Stanislava",
        "Svetlana",
        "Tatyana",
        "Tomislava",
        "Veronika",
        "Vesna",
        "Vladimira",
        "Yaroslava",
        "Yelena",
        "Zaria",
        "Zarya",
        "Zoria",
    ],
    "oracle-character-spanish-male-result": [
        "Alexandre",
        "Alfonso",
        "Alonso",
        "Anthon",
        "Arcos",
        "Arnaut",
        "Arturo",
        "Bartoleme",
        "Benito",
        "Bernat",
        "Blasco",
        "Carlos",
        "Damian",
        "Diego",
        "Domingo",
        "Enrique",
        "Escobar",
        "Etter",
        "Fernando",
        "Franciso",
        "Gabriel",
        "Garcia",
        "Gaspar",
        "Gil",
        "Gomes",
        "Gonzalo",
        "Gostantin",
        "Jayme",
        "Joan",
        "Jorge",
        "Jose",
        "Juan",
        "Machin",
        "Martin",
        "Mateu",
        "Miguel",
        "Nicolas",
        "Pascual",
        "Pedro",
        "Perico",
        "Ramiro",
        "Ramon",
        "Rodrigo",
        "Salvador",
        "Sebastian",
        "Simon",
        "Tomas",
        "Tristan",
        "Valeriano",
        "Ynigo",
    ],
    "oracle-character-spanish-female-result": [
        "Abella",
        "Adalina",
        "Adora",
        "Adriana",
        "Ana",
        "Antonia",
        "Basilia",
        "Beatriz",
        "Bonita",
        "Camila",
        "Cande",
        "Carmen",
        "Catlina",
        "Dolores",
        "Dominga",
        "Dorotea",
        "Elena",
        "Elicia",
        "Esmerelda",
        "Felipina",
        "Francisca",
        "Gabriela",
        "Imelda",
        "Ines",
        "Isabel",
        "Juana",
        "Leocadia",
        "Leonor",
        "Leta",
        "Lucinda",
        "Maresol",
        "Maria",
        "Maricela",
        "Matilde",
        "Melania",
        "Monica",
        "Neva",
        "Nilda",
        "Petrona",
        "Rafaela",
        "Ramira",
        "Rosario",
        "Sofia",
        "Solara",
        "Teresa",
        "Tomasa",
        "Valentia",
        "Veronica",
        "Ynes",
        "Ysabel",
    ],
};
export default characterOracleResults;