const cityOracleResults = {
    "oracle-biome-result": [
        "<a href=\"/oracles/location-oracles#locations-coast\">Coast / Water mass</a>",
        "<a href=\"/oracles/location-oracles#locations-desert\">Desert / Wasteland / Tundra</a>",
        "<a href=\"/oracles/location-oracles#locations-woodlands\">Forest / Shrubland</a>",
        "<a href=\"/oracles/location-oracles#locations-frigid\">Frigid / Taiga / Glacier</a>",
        "<a href=\"/oracles/location-oracles#locations-woodlands\">Jungle / Swamp</a>",
        "<a href=\"/oracles/location-oracles#locations-alpine\">Mountain / Alpine hills</a>",
        "<a href=\"/oracles/location-oracles#locations-plains\">Plains and Fields</a>",
    ],
    "oracle-locations-desert-result": [
        "Battlefield",
        "Canyon / Crevasse",
        "Dry shrubland",
        "Hideout / Lair",
        "Hills / Cliffs",
        "Mesa / Butte",
        "Mine / Cave",
        "Mystical Site",
        "Oasis / Spring",
        "Outpost / Camp",
        "Pass",
        "Road / Trail",
        "Ruin",
        "Village / City",
        "Wall / Fort",
    ],
    "oracle-locations-alpine-result": [
        "Bridge",
        "Canyon / Crevasse",
        "Fjord",
        "Forested Ridge",
        "Hideout / Lair",
        "Mine / Quarry / Cave",
        "Mountain Pass / Avalanche site",
        "Mystical Site",
        "Outpost / Camp",
        "Rapids / Waterfall",
        "Refuge",
        "Ridge / Mountain wall",
        "River / Ravine",
        "Road / Trail",
        "Ruin",
        "Shrub land",
        "Spring",
        "Village / Steading",
        "Wall / Fort",
        "Water pool / Lake",
    ],
    "oracle-locations-plains-result": [
        "Battlefield",
        "Bay / Fjord / Lake",
        "Bridge",
        "Cairn / Grave / Burial Mound",
        "Caravan",
        "Fields / Plain",
        "Hideout / Lair",
        "Hills / Cliffs / Foothills",
        "Hovel / Shack",
        "Mine / Cave",
        "Outpost / Camp / Village",
        "Pond",
        "Ravine / Crevasse",
        "River",
        "Road / Trail",
        "Ruin",
        "Spring",
        "Tree / Grove",
        "Valley",
        "Wall / Fort",
    ],
    "oracle-locations-woodlands-result": [
        "Bog / Fen",
        "Crevasse",
        "Dense Thicket",
        "Giant Tree",
        "Glade",
        "Hideout / Lair",
        "Hills / Cliffs",
        "Hovel / Shack",
        "Hunter’s Nest / Refuge",
        "Logging Area",
        "Mine / Quarry",
        "Mystical Site",
        "Outpost / Camp",
        "Primal Vegetation / Giant Plants",
        "River / Rapids",
        "Road / Trail",
        "Ruin",
        "Spring / Waterfall",
        "Thicket",
        "Village",
    ],
    "oracle-locations-frigid-result": [
        "Battlefield",
        "Bridge",
        "Cairn / Grave / Burial Mound",
        "Canyon / Crevasse",
        "Fjord",
        "Frozen Lake / Glacier",
        "Hideout / Lair / Cave",
        "Hills / Cliffs / Foothills",
        "Ice Bridge / Frozen Crevasse",
        "Icy marsh",
        "Mountain Pass / Avalanche site",
        "Outpost / Camp / Refuge",
        "Rapids / Waterfall",
        "Ridge / Mountain wall",
        "River / Ravine",
        "Road / Trail",
        "Ruin",
        "Tundra Forest",
        "Village / Steading",
        "Wall / Fort",
    ],
    "oracle-locations-coast-result": [
        "Archipelago",
        "Bay",
        "Beach",
        "Cliffs",
        "Coral Reef",
        "Cove",
        "Estuary",
        "Fishing Village",
        "Fjord",
        "Flood / Marsh",
        "Harbor",
        "Ice",
        "Island",
        "Open Water",
        "Peninsula",
        "River Delta",
        "Rocks",
        "Sea Cave / Hideout / Lair",
        "Ship",
        "Storm Debris",
    ],
    "oracle-location-descriptor-result": [
        "Abandoned",
        "Abundant",
        "Ancient",
        "Barren",
        "Beautiful",
        "Big",
        "Blighted",
        "Blocked",
        "Broken",
        "Civilized",
        "Cold",
        "Contested",
        "Corrupted",
        "Dark",
        "Dead",
        "Defended",
        "Dense",
        "Desolate",
        "Diverse",
        "Empty",
        "Expansive",
        "Exposed",
        "Fertile",
        "Flooded",
        "Forgotten",
        "Foul",
        "Grim",
        "Hidden",
        "High",
        "Inaccessible",
        "Isolated",
        "Low",
        "Lush",
        "Mystical",
        "Occupied",
        "Peaceful",
        "Perilous",
        "Protected",
        "Remote",
        "Rich",
        "Rough",
        "Ruined",
        "Savage",
        "Settled",
        "Shadowy",
        "Small",
        "Strange",
        "Wide",
        "Wild",
        "Withered",
    ],
    "oracle-settlement-name-result": [
        [
            "Axe",
            "Black",
            "Bleak",
            "Frost",
            "Gray",
            "Great",
            "Green",
            "Grim",
            "High",
            "Long",
            "Lost",
            "Low",
            "Mourn",
            "New",
            "Raven",
            "Red",
            "Rock",
            "Shield",
            "Stone",
            "Storm",
            "Sword",
            "Thorn",
            "White",
            "Wolf",
            "Wood",
        ],
        [
            "barrow",
            "bridge",
            "brook",
            "cairn",
            "crag",
            "fall(s)",
            "field",
            "ford",
            "hall",
            "haven",
            "hill",
            "home",
            "hope",
            "land",
            "mark",
            "moor",
            "mount",
            "ridge",
            "river",
            "rock",
            "stead",
            "stone",
            "watch",
            "wick",
            "wood",
        ],
    ],
    "oracle-settlement-trouble-result": [
        "A leader falls",
        "Allies become enemies",
        "An innocent is accused",
        "Attack is imminent",
        "Beast on the hunt",
        "Betrayed from within",
        "Broken truce",
        "Conflict with firstborn",
        "Corrupted by dark magic",
        "Cursed past",
        "Dangerous discovery",
        "Dangerous tradition",
        "Dark secret revealed",
        "Debt comes due",
        "Disastrous accident",
        "Dreadful omens",
        "Families in conflict",
        "Important event threatened",
        "Important object is lost",
        "In league with the enemy",
        "In the crossfire",
        "Incompetent leadership",
        "Isolated by brutal weather",
        "Lost caravan",
        "Mysterious murders",
        "Mysterious phenomenon",
        "Natural disaster",
        "Nature strikes back",
        "Old wounds reopened",
        "Outsiders rejected",
        "Production halts",
        "Provisions are scarce",
        "Raiders prey on the weak",
        "Reckless warmongering",
        "Revolt against a leader",
        "Rival settlement",
        "Sickness run amok",
        "Someone is captured",
        "Someone is missing",
        "Stranger causes discord",
        "Trade route blocked",
        "Unjust leadership",
        "Urgent expedition",
        "Vengeful outcast",
        "Wrathful haunt",
    ],
    "oracle-city-name-result": [
        [
            "Ald",
            "Ash",
            "Bel",
            "Bram",
            "Bright",
            "Brim",
            "Buck",
            "Col",
            "Crown",
            "Dagger",
            "Dark",
            "Deep",
            "Dorn",
            "Down",
            "Ever",
            "Fel",
            "Flame",
            "Frost",
            "Gold",
            "Grim",
            "Hammer",
            "Hard",
            "Harren",
            "Helms",
            "Horn",
            "Inns",
            "Kar",
            "Lake",
            "Mal",
            "Mur",
            "Never",
            "Os",
            "Ril",
            "River",
            "Rock",
            "Rose",
            "Roth",
            "Salt",
            "Sand",
            "Sharp",
            "Shep",
            "Stan",
            "Stark",
            "Tar",
            "Torr",
            "Whis",
            "Wick",
            "Wicken",
            "Wind",
            "Yeo",
        ],
        [
            "bridge",
            "brook",
            "burgh",
            "burton",
            "by",
            "cham",
            "chester",
            "cliff",
            "combe",
            "cross",
            "dale",
            "dall",
            "don",
            "enden",
            "est",
            "fall",
            "fast",
            "fell",
            "fields",
            "ford",
            "gate",
            "hal",
            "hall",
            "haven",
            "head",
            "hold",
            "lant",
            "law",
            "lington",
            "lund",
            "mark",
            "more",
            "pass",
            "point",
            "reach",
            "ridge",
            "sall",
            "shaw",
            "shield",
            "song",
            "stock",
            "ton",
            "tower",
            "vale",
            "watch",
            "well",
            "wick",
            "wold",
            "wood",
            "wyn",
        ],
    ],
    "oracle-city-background-result": [
        "Built around a very wealthy noble estate",
        "Built around prominent fortress",
        "Built over ancient ruins",
        "Built over tribal burial cairns",
        "Built to conquer a river mouth",
        "City was taken by current inhabitants from other people",
        "Constructed near woodlands for foresting",
        "Constructed to bring local towns together",
        "Crafted around a set of ancient monoliths",
        "Crafted on the site of a prosperous academy",
        "Gradually built around a consortium of guilds",
        "Location chosen to watch enemy lands",
        "Once acted as a meeting locale for neighboring villages",
        "Once the site of a great battle",
        "Rebuilt completely after a terrible fire",
        "Site chosen for its excellent defensible position",
        "Site of a prosperous trading post",
        "Site of an ancient peace treaty between warring neighbors",
        "To help secure a border with a nearby nation",
        "Was funded by wealthy adventurers where they chose to settle",
    ],
    "oracle-city-history-result": [
        "Corruption split the government, creating a vaccuum of power as disparate forces vie for control",
        "Cultist plot caused many deaths and paranoia, leaving many commoners xenophobic and guarded",
        "Destruction of local basilica created hopelessness, demoralizing even the least religious people",
        "Economic recession caused hardship among the working classes and only now is the city recovering",
        "Enemy invasion was barely repelled, leaving the leadership of the city in disarray",
        "Flooding from a broken levee toppled walls and ruptured infrastructure",
        "Frequent monster attacks against the city have forced an increase in taxes for guards and defenses",
        "Guild collapse caused shift in goverment and financial problems that rippled throughout the city",
        "Incurable disease ravaged every neighborhood, regardless of wealth",
        "Magical disaster has citizens distrusting spell casters",
        "Massive fire raged, destroying large sections of the city and leaving many people homeless",
        "Monetary influx allowed time of great prosperity",
        "Neighborhood battles once nearly tore city apart",
        "Plague nearly wiped out the original founders",
        "Racial animosity and war have marred every stage of the city’s history",
        "Religious upheaval turned the citizens against one another and threatened to cripple the city",
        "Residue and resentment from a recent civil war are still felt today, dividing the city into two camps",
        "Riots against the government destroyed civic centers, cultural halls, monuments, and prisons",
        "Usurper conquered the city in a near-bloodless coup years ago",
        "Wharf collapse caused the docks to be rebuilt anew with great care",
    ],
    "oracle-city-description-result": [
        "Alabaster and cobalt stone buildings present a beautiful facade, hiding the decayed city center.",
        "Arches and raised bridges crisscross the multi-level city, with a palace at the apex. No outer walls.",
        "Bright from a distance, with obvious great temples and churches. No wall. Patrolled by paladins.",
        "Buildings and boardwalk roadways settle on stilts above a swamp. Lanterns flicker at each doorway.",
        "Buildings built on hilly ground, nestled inside well-guarded walls. Central main tower complex.",
        "Built and rebuilt over hundreds of years, the architecture is a hodgepodge of classic and neoclassic.",
        "Built on a cliff side. Wealthier citizens live at the top. Single, towering government building.",
        "Built on a sloping field. Government buildings at the wall perimeter. Residents/businesses in center.",
        "Built on rocky ground, a towering stone bridge spans across the river. Tall houses cluster together.",
        "Business town. Elaborate guild manors, businesses, and workshops. Sprawling trade center.",
        "City straddles a giant rocky hill with buildings and roads winding around it. A castle sits at the apex.",
        "Cobbled together with various stones and bricks. The city lacks cohesion or planning.",
        "Dull colorless buildings moist with dew from lakeside mist. Simple wooden palisade wall.",
        "Gothic towers and monuments paint the city a dreary shade, as the walls pen in the citizens.",
        "Gothic, spiked walls of black basalt surround this circular city with an abundance of watchtowers.",
        "Half city, half wilderness. Bushes, trees, gardens, and lawns integrate perfectly with buildings.",
        "Huge deepwater port lines one side of the city, and its river continues inland around the solid walls.",
        "Large central city has a road leading down to a second, smaller city dock ward by the seaside.",
        "Lower city lies in shadow of cliffside upper district with a single road leading between the two.",
        "Maze of walls intersect the city, combined with ancient monolithic walls of another age.",
        "Mighty metropolis with a central park. Defensive walls and numerous well-guarded gate towers.",
        "Multiple government buildings. Castle flies many flags. Archers walk the walls.",
        "Narrow, twisting, forked roads cut through the two-story city blocks, making navigation difficult.",
        "Nestled atop a large plateau overlooking a trade route. Buildings are sometimes set in the cliff.",
        "Old and in need of repair. Walls crumble. No civic pride is evident. Brickwork lacks mortar.",
        "On the edge of a peninsula, spanning out to all three sides and working inland.",
        "Oval city with five equal and distinct wards surrounding a central keep, watchtower, and citadel.",
        "Plenty of unique features grace the city, including a hedge maze and gap-spanning stone bridges.",
        "Seaside port. New and old neighborhoods. Variety of clothing styles and market goods.",
        "Set inside a huge gap along a mountain pass that guards all passers. The pass rests between nations.",
        "Simple woodside town with clusters of like-minded businesses and a nearby garrison fortification.",
        "Smoky and hazy from a distance thanks to numerous workshops, tanneries, and smithies.",
        "Unwalled city sprawled over a hilly region. Well-maintained roads and patrols.",
        "Wide streets and tall buildings focus upon a massive embassy, where the terminating vista points.",
    ],
    "oracle-city-industry-result": [
        "Artists",
        "Bakeries and brewing",
        "Carpentry/construction",
        "Cartwrights/wainwrights",
        "Coal mining",
        "Colleges/universities",
        "Copper mining",
        "Farming (surrounding land)",
        "General mining",
        "Gold mining",
        "Guilds",
        "Herding (surrounding land)",
        "Iron mining",
        "Libraries and museums",
        "Masonry/construction",
        "Mills",
        "Shipwrights",
        "Silver mining",
        "Smithing",
        "Trade",
    ],
    "oracle-city-location-result": [
        "Abandoned structure",
        "Amphitheater",
        "Apartment block",
        "Apothecary",
        "Aqueduct",
        "Archway (spanning)",
        "Arena",
        "Armory",
        "Art gallery",
        "Asylum",
        "Bank",
        "Barn",
        "Barracks",
        "Basilica",
        "Bathhouse",
        "Bazaar",
        "Blockhouse",
        "Brewery",
        "Brickhouse",
        "Bridge",
        "Brothel",
        "Bunker",
        "Capitol",
        "Caravan quarter",
        "Castle",
        "Castle district",
        "Cathedral",
        "Chapel",
        "Chateau",
        "Church",
        "Circus (chariot racing)",
        "Citadel",
        "City gate",
        "City hall",
        "Coliseum",
        "Concert hall",
        "Condominium",
        "Consulate",
        "Cottage",
        "Courthouse",
        "Defensive wall",
        "Docks/Harbor",
        "Dumas",
        "Embassy",
        "Farm house",
        "Fort",
        "Fortification",
        "Fortress",
        "Fortress",
        "Forum",
        "Foundry",
        "Gambling den",
        "Garden/Greenhouse",
        "General store",
        "Granary",
        "Graveyard",
        "Gristmill",
        "Guard and jail district",
        "Guard tower",
        "Guardhouse",
        "Guildhouse",
        "Hay loft",
        "Hospital",
        "Inn",
        "Inn and tavern district",
        "Kiln (outdoor)",
        "Laboratory",
        "Library",
        "Magic district with towers",
        "Manor",
        "Market (outdoor)",
        "Market building",
        "Market district with open ground",
        "Meadhall",
        "Military quarter",
        "Mill",
        "Mining",
        "Monastery",
        "Noble quarter",
        "Palace",
        "Prison district",
        "Red-light district",
        "Residential district",
        "Residential district, wealthy",
        "Slave quarter",
        "Slum district",
        "Smithy",
        "Stable",
        "Stronghold",
        "Tannery district",
        "Tavern",
        "Temple district with graveyard or necropolis",
        "Theater district",
        "Towers",
        "Villa",
        "Walled keep",
        "Warehouse district",
        "Watchtower",
        "Waterfront with docks",
        "Windmill",
    ],
    "oracle-city-tavern-result": [
        "<a>Admiral’s.</a><br/> This place is run by a navy man, who uses many colorful sayings.",
        "<a>Ale Well.</a><br/> Only ale is served here.",
        "<a>Bean Inn.</a><br/> This place is covered with trellises during the winter and beans in summer.",
        "<a>Bell Tower.</a><br/> A tavern was built around the old bell tower.",
        "<a>Bellmaker’s.</a><br/> This place is run by the town’s bell maker. His shop is in the back of the building.",
        "<a>Black Portrait.</a><br/> A large portrait of black paint sits above the mantle.",
        "<a>Boomer’s.</a><br/> The owner’s bellowing voice shakes the rafters. His name is Tiny.",
        "<a>Brine Cat.</a><br/> Named for a mythical creature that lives in the brine and eats sea birds and urchins.",
        "<a>Bull’s Horns.</a><br/> A large set of horns graces the front door, far too large for an ordinary bull.",
        "<a>Burrow.</a><br/> Caters to small patrons.",
        "<a>Chapel.</a><br/> This building was once a church. Some of the stained glass remains in the windows.",
        "<a>Cheaters.</a><br/> The owner loves retelling the tale of the green slime which robbed him of his arm.",
        "<a>Chessman.</a><br/> If a patron beats the owner at chess he gets free room and board for one night.",
        "<a>Cloister.</a><br/> Loud voices and noises are prohibited in this otherwise normal tavern.",
        "<a>Coop.</a><br/> The entire second floor houses chickens. Eggs and chicken dishes are served every meal.",
        "<a>Copper Drake.</a><br/> A copper dragon head leans out over the bar. It blinks occasionally.",
        "<a>Cracked Pot.</a><br/> Cheap mutton and bear meat fill the menu, along with watered-down drinks.",
        "<a>Cricket’s.</a><br/> Run by a bard named Cricket who plays one song for the crowd every night.",
        "<a>Cudgel.</a><br/> A huge wooden club hangs from the front of the building, with the rune for storm on it.",
        "<a>Dancer and the Dark Mage.</a><br/> This place is run by twin brothers who are exact opposites.",
        "<a>Dancing Bear.</a><br/> This place boasts a caged dire bear, which seems well treated if cramped.",
        "<a>Dart Room.</a><br/> Nightly dart-throwing contests bring in most of the business here.",
        "<a>Decimator’s.</a><br/> The intelligent sword that hangs on the mantle sometimes tell tales of past glories.",
        "<a>Deer’s Perch.</a><br/> A wooden carved deer perches on a pole jutting from the front of the building.",
        "<a>Dragon’s Horn.</a><br/> This place is run by former prostitutes, of both sexes and different races.",
        "<a>Ebby’s Galley.</a><br/> Inside the place is furnished to resemble a ship’s galley, including porthole windows.",
        "<a>Emporium.</a><br/> An ex-adventurer runs this place. It is decorated with odds and ends from his quests.",
        "<a>Endless Decanter.</a><br/> Named after the magic item of the same name that dispenses ale.",
        "<a>Errant Fighter.</a><br/> Though the owner is never around, the staff continue to work the tavern.",
        "<a>Fallen Star.</a><br/> A meteor fell through the roof here. The owner left it where it fell.",
        "<a>Father’s Tavern.</a><br/> Shiny trinkets hang from the rafters on string. Contributions are welcome.",
        "<a>Feral Daughter.</a><br/> The owner refuses to serve anything from a farm, only wild game.",
        "<a>Fern’s.</a><br/> Guard dogs are chained to the back door and to the cellar door. The windows are barred.",
        "<a>Fish Story.</a><br/> A sea serpent’s head hangs above the bar. The owner loves to talk about it.",
        "<a>Fisher’s.</a><br/> A large net covers the ceiling of the place; assorted nautical and beach finds adorn it.",
        "<a>Gladiator’s Hole.</a><br/> Exotic weapons adorn the walls of this tavern.",
        "<a>Griffin’s Nest.</a><br/> A nest, sized for a griffin, rests on the flat roof of this place. There are feathers in it.",
        "<a>Hag’s End.</a><br/> The proprietor is a comely young lass with a mysterious past.",
        "<a>Hellgate.</a><br/> This place was built around a massive stone portal. One of the stones is missing.",
        "<a>Hero’s Horne.</a><br/> Long ago the horn was used to rally the townsfolk against attacks.",
        "<a>Hive.</a><br/> A bakery run by beekeepers, they serve mead and honeyed cakes, and sell beeswax candles.",
        "<a>Hospice.</a><br/> This is an inn as well as a temple to the local deity of travelers.",
        "<a>Houndsman.</a><br/> The owner sets his hounds free at night to protect horses and guests from wolves.",
        "<a>Hunter’s Blind.</a><br/> A tavern that serves as a mercantile for hunting supplies (blinds, nets, traps, etc.).",
        "<a>Iron Urn.</a><br/> Named for the ale that is served in a three-foot tall iron flask.",
        "<a>Jacques’.</a><br/> An effette and regal drinking hall for accomplished adventurers and gentry.",
        "<a>Jester’s.</a><br/> The owner is rarely seen, but the inn‘s mainstay is Bremen, who always has a smile.",
        "<a>Kirin’s Gift.</a><br/> There is only one barrel behind the bar, and all types of drinks can be taken from it.",
        "<a>Knaves.</a><br/> The jester head outside and the constant music make this a well-known “town secret.”",
        "<a>Laurel’s.</a><br/> Named for the blind old woman who sits near the fire, who was once a local hero.",
        "<a>Lazy Dog.</a><br/> Known for its extensive daytime drinking, poor lighting, and generous tab system.",
        "<a>Left and Right.</a><br/> A meadhall for military men and gladiators. There are no bards or minstrels here.",
        "<a>Lighthouse.</a><br/> Obviously once a lighthouse, it is now an inn, with a single suite at the top.",
        "<a>Logar’s Helm.</a><br/> The first two floors are stone and the roof is a storm giant’s metal helmet.",
        "<a>Lyre’s Tale.</a><br/> Run by a one-legged bard, who specializes in riddles and puzzles.",
        "<a>Magog.</a><br/> A dank, horrid tavern catering to antisocial mitfits and the like.",
        "<a>Medusa’s Garden.</a><br/> Stone statues can be found everywhere, but they are obviously crafted by hand.",
        "<a>Mighty Quill.</a><br/> Run by a bear of a man who writes ballads during slow hours and may sing if asked.",
        "<a>Misty Tavern.</a><br/> Built in a depression, it fills with fog during morning and evening hours.",
        "<a>Mosaic Lantern.</a><br/> A six-foot-tall steel lantern sits outside; the panes are stained glass.",
        "<a>Mosaics.</a><br/> The walls, both inside and out, are covered with tile mosaics of fantastic creatures.",
        "<a>Moss Room.</a><br/> Boasts four stories, two of them underground, where folks gather in the hot months.",
        "<a>Muddy Greyeye.</a><br/> No one knows the origin of this tavern’s name, it having been built 100 years ago.",
        "<a>Mug.</a><br/> The owner is a wizard and sells or trades sobering spells for a high cost.",
        "<a>Museum.</a><br/> This place used to be a manor house and many antiques can be found within.",
        "<a>Ole Crick’s.</a><br/> Old Crick has long since passed on, but the name remains.",
        "<a>Orange Cat.</a><br/> The place is overrun with cats, all orange.",
        "<a>Painted Hall.</a><br/> The tavern runs in the front, with gambling and escorts in the back (for a price).",
        "<a>Paper House.</a><br/> This place has Asian-style rugs and paper-paneled room dividers.",
        "<a>Pink Moose.</a><br/> Some joker keeps painting the wooden statue of a moose outside this place.",
        "<a>Piper’s.</a><br/> The owner’s blind daughter plays the pipes after dark.",
        "<a>Portland.</a><br/> The owner secretly trades in slavery and blackmarket goods, ferrying away drunks.",
        "<a>Post.</a><br/> Full-service stables take up most of the building and the interior is a faux stable.",
        "<a>Queen’s Rounds.</a><br/> Known for ample portions and expensive drink. Not everyone is allowed in.",
        "<a>Rainbow Round.</a><br/> All the lanterns here have glass prisms, painting the room in rainbows.",
        "<a>Roost.</a><br/> Run by several older widows, who make quilts and crafts when business is slow.",
        "<a>Round World.</a><br/> Run by a man who believes the world is round. He brews the finest ale.",
        "<a>Rovers.</a><br/> A roadhouse at the edge of town, The drinks are cheap and the cots plentiful.",
        "<a>Rows and Weeds.</a><br/> Mostly a drinking hall for farmers and daylaborers, with no entertainment.",
        "<a>Rusted Drake.</a><br/> Run by a family that migrated from far across the sea with stories of lands beyond.",
        "<a>Rusty Anchor.</a><br/> Half of a large rusty anchor sits upon the mantle. The owner is free with the story.",
        "<a>Sand Pit.</a><br/> Instead of sawdust on the floor, this inn has sand nearly a foot deep.",
        "<a>Shelby’s.</a><br/> The husband and wife owners both share the same first name.",
        "<a>Silent Dancer.</a><br/> The contortionist dancers here don’t speak to anyone, but work for tips.",
        "<a>Silver Stone.</a><br/> Stones set into mortar shine like mica, brightening the common room.",
        "<a>Sleeping Dragon.</a><br/> The owner escorts patrons to the basement; a window shows a sleeping dragon.",
        "<a>Slippery Pig.</a><br/> The owner has the fastest pigs in town and provides them for greased-pig contests.",
        "<a>Spirits.</a><br/> For extra silver the barkeep will read fortunes with cards. The locals swear by him.",
        "<a>Spooky’s.</a><br/> Each night the owner sits in the darkened common room and tells scary tales.",
        "<a>Squirrel’s.</a><br/> Overrun by squirrels, which take food from patrons’ hands, whether offered or not.",
        "<a>Stone Cow.</a><br/> The cow statue seems very lifelike, almost unnaturally so.",
        "<a>Stone Inn.</a><br/> Made entirely out of stone, with small wood stoves in each room for warmth.",
        "<a>The Corsair.</a><br/> Owned by an ex-merchant marine who spins tales of the sea (true or otherwise).",
        "<a>The Eagle’s Landing.</a><br/> Built atop a small knoll, the tavern is known for its all-night parties.",
        "<a>The Gorgon’s Grog.</a><br/> Named for an infamous (and potent) drink that no one can drink two of.",
        "<a>The Harbinger’s Stein.</a><br/> Rumors persist that the drinks here kill, but those are just rumors…",
        "<a>The Midwife’s.</a><br/> The owner is also the town’s midwife and chief gossipmonger.",
        "<a>The Moor.</a><br/> Nowhere near water, the tavern still boasts all manner of shipping adornments.",
        "<a>The Pond.</a><br/> Sits on the bank of a large pond. The locals rave about the fish, eels, and frogs served.",
        "<a>The Safehouse.</a><br/> Run by smugglers and thieves, the tavern is among the safest places in the city.",
    ],
    "oracle-incursion-theme-result": [
        "<a>Ancient</a><br/>This place holds secrets of a bygone age.",
        "<a>Contested</a><br/>This place is an active warzone.",
        "<a>Corrupted</a><br/>This place is tainted by dark magic.",
        "<a>Flooded</a><br/>Murky waters have overtaken this place.",
        "<a>Fortified</a><br/>Foes defend this place against intruders.",
        "<a>Frozen</a><br/>The cold has befallen on this place.",
        "<a>Hallowed</a><br/>The faithful worship here.",
        "<a>Haunted</a><br/>Restless spirits are bound to this place.",
        "<a>Infested</a><br/>Foul creatures dwell here.",
        "<a>Jurassic</a><br/>Primal life rules over this land lost in time.",
        "<a>Ravaged</a><br/>Time, disaster or strife has taken their toll here.",
        "<a>Volcanic</a><br/>Heat and noxious gases fill this place.",
        "<a>Wild</a><br/>Nature prevails in this untouched place.",
    ],
    "oracle-incursion-domain-result": [
        "<a href=\"/oracles/location-oracles#incursion-name-barrow\">Barrow</a><br/>The dead are enshrined here.",
        "<a href=\"/oracles/location-oracles#incursion-name-cavern\">Cavern</a><br/>A place of stone and darkness.",
        "<a href=\"/oracles/location-oracles#incursion-name-ruin\">Desert</a><br/>Sand, rock and heat everywhere.",
        "<a href=\"/oracles/location-oracles#incursion-name-pass\">Eyrie</a><br/>Rocky spires home to aerial creatures.",
        "<a href=\"/oracles/location-oracles#incursion-name-cavern\">Frozen Cavern</a><br/>A place of deep caves and enduring cold.",
        "<a href=\"/oracles/location-oracles#incursion-name-icereach\">Icereach</a><br/>A frigid landscape formed of frozen seas.",
        "<a href=\"/oracles/location-oracles#incursion-name-jungle\">Jungle</a><br/>An exotic rainforest full of dangers.",
        "<a href=\"/oracles/location-oracles#incursion-name-mine\">Mine</a><br/>Tunnels dug greedily and deep.",
        "<a href=\"/oracles/location-oracles#incursion-name-pass\">Pass</a><br/>Treacherous paths over high mountains.",
        "<a href=\"/oracles/location-oracles#incursion-name-ruin\">Ruin</a><br/>The crumbling legacy of a dead civilization.",
        "<a href=\"/oracles/location-oracles#incursion-name-seacave\">Sea Cave</a><br/>Stone passages carved by ocean waves.",
        "<a href=\"/oracles/location-oracles#incursion-name-seacave\">Sea Voyage</a><br/>At the mercy of the winds and currents.",
        "<a href=\"/oracles/location-oracles#incursion-name-ruin\">Settlement</a><br/>Multiple structures fill this place.",
        "<a href=\"/oracles/location-oracles#incursion-name-jungle\">Shadowfen</a><br/>A primeval marsh, cloaked in mist.",
        "<a href=\"/oracles/location-oracles#incursion-name-seacave\">Shipwreck</a><br/>A huge ship crashed upon rocks or reef.",
        "<a href=\"/oracles/location-oracles#incursion-name-stronghold\">Stronghold</a><br/>A fortress secured against trespassers.",
        "<a href=\"/oracles/location-oracles#incursion-name-tanglewood\">Tanglewood</a><br/>A perilous forest of eternal shadow.",
        "<a href=\"/oracles/location-oracles#incursion-name-ruin\">Tundra</a><br/>A place windswept, cold and dry.",
        "<a href=\"/oracles/location-oracles#incursion-name-underkeep\">Underkeep</a><br/>An age-old subterranean dungeon.",
        "<a href=\"/oracles/location-oracles#incursion-name-stronghold\">Ziggurat</a><br/>A temple dedicated to a forgotten deity.",
    ],
    "oracle-incursion-name-barrow-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Barrow",
                "Crypt",
                "Grave",
                "Mound",
                "Sepulcher",
                "Tomb",
            ],
        }
    },
    "oracle-incursion-name-cavern-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Abyss",
                "Caverns",
                "Caves",
                "Chasm",
                "Depths",
                "Hollow",
                "Lair",
                "Rift",
                "Tunnels",
                "Warren",
            ],
        }
    },
    "oracle-incursion-name-icereach-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Barrens",
                "Expanse",
                "Icemark",
                "Reach",
                "Waste",
                "Wintertide",
            ],
        }
    },
    "oracle-incursion-name-mine-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Cut",
                "Dig",
                "Forge",
                "Lode",
                "Mine",
                "Tunnels",
            ],
        }
    },
    "oracle-incursion-name-pass-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Cliffs",
                "Crag",
                "Cut",
                "Gap",
                "Gorge",
                "Heights",
                "Highlands",
                "Pass",
                "Reach",
                "Ridge",
            ],
        }
    },
    "oracle-incursion-name-ruin-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Citadel",
                "Enclave",
                "Fortress",
                "Hall",
                "Keep",
                "Sanctuary",
                "Sanctum",
                "Spire",
                "Temple",
                "Tower",
            ],
        }
    },
    "oracle-incursion-name-seacave-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Caves",
                "Channel",
                "Cove",
                "Gouge",
                "Hollow",
                "Pools",
            ],
        }
    },
    "oracle-incursion-name-jungle-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Bog",
                "Fen",
                "Floodlands",
                "Lowland",
                "Marsh",
                "Mire",
                "Morass",
                "Quagmire",
                "Slough",
                "Wetlands",
            ],
        }
    },
    "oracle-incursion-name-stronghold-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Bastion",
                "Citadel",
                "Fortress",
                "Garrison",
                "Haven",
                "Keep",
                "Outpost",
                "Refuge",
                "Sanctuary",
                "Watch",
            ],
        }
    },
    "oracle-incursion-name-tanglewood-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Bramble",
                "Briar",
                "Forest",
                "Tangle",
                "Thicket",
                "Weald",
                "Wilds",
                "Wood",
            ],
        }
    },
    "oracle-incursion-name-underkeep-result": {
        "template": [
            "{description} {place}",
            "{place} of {detail}",
            "{place} of {description} {detail}",
        ],
        "tables":  {
            "description": [
                "Abyssal",
                "Ashen",
                "Barren",
                "Black",
                "Blighted",
                "Bloodied",
                "Bloodstained",
                "Broken",
                "Chaotic",
                "Crimson",
                "Crumbling",
                "Cursed",
                "Dark",
                "Deep",
                "Desecrated",
                "Dreaded",
                "Elder",
                "Endless",
                "Fallen",
                "Fell",
                "Flooded",
                "Forbidden",
                "Forgotten",
                "Forsaken",
                "Frozen",
                "Grey",
                "Grim",
                "Haunted",
                "Hidden",
                "High",
                "Infernal",
                "Iron",
                "Lost",
                "Nightmare",
                "Ruined",
                "Sacred",
                "Scarred",
                "Scorched",
                "Secret",
                "Shattered",
                "Shrouded",
                "Silent",
                "Silver",
                "Sundered",
                "Sunken",
                "Tainted",
                "Undying",
                "Unknown",
                "Wasted",
                "White",
            ],
            "detail": [
                "Ash",
                "Bane",
                "Banishment",
                "Blades",
                "Blight",
                "Blood",
                "Bone",
                "Corruption",
                "Darkness",
                "Daybreak",
                "Desolation",
                "Despair",
                "Doom",
                "Dread",
                "Fate",
                "Frost",
                "Fury",
                "Gloom",
                "Hope",
                "Iron",
                "Isolation",
                "Lament",
                "Lies",
                "Light",
                "Madness",
                "Mist",
                "Nightfall",
                "Power",
                "Prophecy",
                "Rot",
                "Runes",
                "Sadness",
                "Sanctuary",
                "Secrets",
                "Shadow",
                "Silence",
                "Souls",
                "Specters",
                "Spring",
                "Stone",
                "Storms",
                "Strife",
                "Terror",
                "Torment",
                "Treachery",
                "Truth",
                "Twilight",
                "War",
                "Winter",
                "Wrath",
            ],
            "place": [
                "Catacomb",
                "Chambers",
                "Den",
                "Hall",
                "Labyrinth",
                "Maze",
                "Pit",
                "Sanctum",
                "Underkeep",
                "Vault",
            ],
        }
    },
    "oracle-incursion-danger-result": [
        "A disturbing truth is revealed",
        "Alarm trigger",
        "Ancient disease or contamination",
        "Ancient evil resurgent",
        "Ancient mechanism or trap",
        "Artifact of terrible meaning or power",
        "Artifact with a hidden danger",
        "Aspect of the faith beguiles you",
        "Bitter chill",
        "Blocked or broken passage",
        "Blocked or guarded path",
        "Caught in the open",
        "Cave-in",
        "Chokepoint",
        "Concealing or disorienting mist",
        "Corruption marks you",
        "Crumbling architecture",
        "Crumbling chasm",
        "Dark ritual in progress",
        "Death makes its presence known",
        "Deep water blocks the path",
        "Denizen attacks without warning",
        "Denizen blocks the path",
        "Denizen controls dark magic",
        "Denizen corrupted by dark magic",
        "Denizen defends their sanctum",
        "Denizen enacts the will of their god",
        "Denizen funnels you down a new path",
        "Denizen guards this area",
        "Denizen guided by a greater threat",
        "Denizen haunts this area",
        "Denizen hunts",
        "Denizen lairs here",
        "Denizen lays in wait",
        "Denizen lures you into a trap",
        "Denizen lurks in darkness",
        "Denizen makes a costly demand",
        "Denizen on guard",
        "Denizen patrols the area",
        "Denizen protects an ancient secret",
        "Denizen ready to sound the alarm",
        "Denizen reveals surprising cleverness",
        "Denizen reveres an ancient power",
        "Denizen seeks martyrdom",
        "Denizen seizes your body or mind",
        "Denizen sets an ambush",
        "Denizen spawned from dark magic",
        "Denizen stalks you",
        "Denizen takes or destroys something",
        "Denizen taunts or lures you",
        "Denizen undermines the path",
        "Denizens converge on this area",
        "Denizens swarm and attack",
        "Dire warnings of a long-buried danger",
        "Disorienting reflections",
        "Disturbing evidence of ancient wrongs",
        "Divine manifestations",
        "Dread harbingers of a greater magic",
        "Embodiment of a god or myth",
        "Entangling plant life",
        "Fissure or sinkhole",
        "Flooding",
        "Foul weather",
        "Fracturing ice",
        "Frightening visions",
        "Grave goods with hidden dangers",
        "Greater purpose is revealed",
        "Hazardous architecture or terrain",
        "Hidden quagmire",
        "Illusions lead you astray",
        "Innocents held in thrall",
        "Lingering effects of a dark ritual",
        "Living relics of a lost age",
        "Mystic barrier or ward",
        "Mystic trap or trigger",
        "Nefarious plans revealed",
        "Others seek power or knowledge",
        "Perilous climb or descent",
        "Pets or underlings",
        "Prophecies reveal a dark fate",
        "Protective ward or barrier",
        "Revelations of a terrible truth",
        "Secret of the faith is revealed",
        "Sudden, shocking manifestation",
        "The environment is used against you",
        "Toxic environment",
        "Toxic or sickening environment",
        "Trap or snare",
        "Trickery leads you astray",
        "True nature of this place is revealed",
        "Unexpected alliance revealed",
        "Unexpected disciples are revealed",
        "Unexpected leader is revealed",
        "Unsettling sounds or foreboding signs",
        "Victim’s horrible fate is revealed",
    ],
    "oracle-location-feature-aspect-result": [
        "Abandoned",
        "Abundant",
        "Active",
        "Ancient",
        "Blocked",
        "Broken",
        "Collapsed",
        "Complex",
        "Confined",
        "Crafted",
        "Dead",
        "Deadly",
        "Decaying",
        "Deep",
        "Defended",
        "Depleted",
        "Destroyed",
        "Elevated",
        "Ensnaring",
        "Expansive",
        "Flooded",
        "Foreboding",
        "Forgotten",
        "Fortified",
        "Foul",
        "Fragile",
        "Guarded",
        "Hidden",
        "Inaccessible",
        "Isolated",
        "Makeshift",
        "Marked",
        "Moving",
        "Mysterious",
        "Mystical",
        "Natural",
        "Open",
        "Pillaged",
        "Ruined",
        "Sacred",
        "Sealed",
        "Secret",
        "Sunken",
        "Toxic",
        "Trapped",
        "Treacherous",
        "Unnatural",
        "Unstable",
        "Unusual",
        "Veiled",
    ],
    "oracle-location-feature-focus-result": [
        "Alarm",
        "Attack",
        "Boundary",
        "Breach",
        "Container",
        "Corruption",
        "Craft",
        "Creature",
        "Crossing",
        "Darkness",
        "Death",
        "Debris",
        "Denizen",
        "Enclosure",
        "Entry",
        "Environment",
        "Equipment",
        "Exit",
        "Function",
        "Grave",
        "Habitation",
        "Hideaway",
        "History",
        "Illumination",
        "Information",
        "Lair",
        "Location",
        "Material",
        "Message",
        "Nature",
        "Obstacle",
        "Opening",
        "Passage",
        "Person",
        "Power",
        "Prisoner",
        "Refuge",
        "Remains",
        "Resource",
        "Route",
        "Shelter",
        "Sign",
        "Supply",
        "Threshold",
        "Trail",
        "Trap",
        "Trigger",
        "Valuables",
        "Water",
        "Weapon",
    ],
    "oracle-incursion-feature-barrow-result": [
        "Burial chambers",
        "Maze of narrow passages",
        "Shrine",
        "Stately vault",
        "Offerings to the dead",
        "Statuary or tapestries",
        "Remains of a grave robber",
        "Mass grave",
        "Exhumed corpses",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-cavern-result": [
        "Twisting passages ",
        "Cramped caves",
        "Vast chamber",
        "Subterranean waterway",
        "Cave pool",
        "Natural bridge",
        "Towering stone formations",
        "Natural illumination",
        "Dark pit",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-icereach-result": [
        "Plains of ice and snow",
        "Seawater channel",
        "Icy highlands",
        "Crevasse",
        "Ice floes",
        "Ship trapped in ice",
        "Animal herd or habitat",
        "Frozen carcass",
        "Camp or outpost",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-mine-result": [
        "Cramped tunnels",
        "Mine works",
        "Excavated chamber",
        "Mineshaft",
        "Collapsed tunnel",
        "Cluttered storage",
        "Housing or common areas",
        "Flooded chamber",
        "Unearthed secret",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-pass-result": [
        "Winding mountain path",
        "Snowfield or glacial rocks",
        "River gorge",
        "Crashing waterfall",
        "Highland lake",
        "Forgotten cairn",
        "Bridge",
        "Overlook",
        "Camp or outpost",
        "Giant rocky spires",
        "Small cavern or nest",
        "Spiraling tower rock",
        "Table-like rock precariously balanced",
        "Cracked rocks ready to tumble",
        "Narrow passages",
        "Natural bridge",
        "Narrow path",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-ruin-result": [
        "Crumbling corridors and chambers",
        "Collapsed architecture",
        "Rubble-choked hall",
        "Courtyard",
        "Archive or library",
        "Broken statuary or fading murals",
        "Preserved vault",
        "Temple to forgotten gods",
        "Mausoleum",
        "Cluster of small boulders",
        "Scrub-like plants",
        "Abandoned house",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-seacave-result": [
        "Watery tunnels",
        "Eroded chamber",
        "Flooded chamber",
        "Vast chamber",
        "Dry passages",
        "Freshwater inlet",
        "Rocky island",
        "Waterborne debris",
        "Shipwreck or boat",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-jungle-result": [
        "Narrow path through a fetid bog",
        "Stagnant waterway",
        "Flooded thicket",
        "Island of dry land",
        "Submerged discovery",
        "Preserved corpses",
        "Overgrown structure",
        "Tall reeds",
        "Camp or outpost",
        "Thick canopy blocking the light",
        "Vine-strewn paths",
        "Humanoid-sized leaves",
        "Strangely colored flora",
        "Open sky with dense undergrowth",
        "Tall trees swaying in the wind",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-stronghold-result": [
        "Connecting passageways",
        "Barracks or common quarters",
        "Large hall",
        "Workshop or library",
        "Command center or leadership",
        "Ladder or stairwell",
        "Storage",
        "Kitchen or larder",
        "Courtyard",
        "Stone staircase",
        "Ceremonial chamber",
        "Labyrinthine passages",
        "Altar of sacrifice",
        "Towering statues",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-tanglewood-result": [
        "Dense thicket",
        "Overgrown path",
        "Waterway Clearing",
        "Elder tree",
        "Brambles",
        "Overgrown structure",
        "Rocky outcrop",
        "Camp or outpost",
        "Maze of giant roots",
        "Thick canopy blocking the light",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
    "oracle-incursion-feature-underkeep-result": [
        "Carved passages",
        "Hall or chamber",
        "Stairs into the depths",
        "Grand doorway or entrance",
        "Tomb or catacombs",
        "Rough-hewn cave",
        "Foundry or workshop",
        "Shrine or temple",
        "Imposing architecture or artistry",
        "Something unusual or unexpected (<a href=\"/oracles/location-oracles#location-feature\">Location Feature</a>)",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-theme\">theme</a>",
        "You transition into a new <a href=\"/oracles/location-oracles#incursion-domain\">domain</a>",
    ],
};
export default cityOracleResults;