const miscOracleResults = {
    "oracle-combat-action-result": [
        "Block a path or cut off an objective",
        "Cause reckless damage",
        "Change weapons or tactics",
        "Compel a surrender or concession",
        "Coordinate with allies",
        "Corner, trap, or entangle",
        "Counter or reflect an attack",
        "Create a distraction",
        "Destroy something or render it useless",
        "Fall back or stand off",
        "Hide or sneak",
        "Intimidate, taunt, or frighten",
        "Leverage the advantage of a weapon or ability",
        "Leverage the terrain or surroundings",
        "Lure into a vulnerable position",
        "Make a cautious or probing attack",
        "Make a ferocious or powerful attack",
        "Make a precise or careful attack",
        "Make a sacrificial attack",
        "Make an indirect attack",
        "Move in close or grapple",
        "Nullify a system, device, or weapon",
        "Overrun a position",
        "Perform a feint or trick",
        "Press an advantage",
        "Provoke a careless response",
        "Ready a decisive action",
        "Shift the fight to a new area",
        "Summon aid or reinforcements",
        "Take cover or bolster defenses",
        "Use an unexpected weapon or ability",
        "Weaken defenses",
    ],
    "oracle-trap-event-result": [
        "Ambush",
        "Attack",
        "Block",
        "Break",
        "Change",
        "Collapse",
        "Conceal",
        "Create",
        "Crush",
        "Cut",
        "Divert",
        "Drop",
        "Enclose",
        "Entangle",
        "Imitate",
        "Lure",
        "Move",
        "Obscure",
        "Puncture",
        "Release",
        "Smother",
        "Snare",
        "Summon",
        "Surprise",
        "Trigger",
    ],
    "oracle-trap-component-result": [
        "Alarm",
        "Barrier",
        "Cold",
        "Darkness",
        "Debris",
        "Decay",
        "Denizen",
        "Earth",
        "Fall",
        "Fear",
        "Fire",
        "Light",
        "Magic",
        "Overhead",
        "Passage",
        "Path",
        "Pit",
        "Poison",
        "Projectile",
        "Stone",
        "Terrain",
        "Toxin",
        "Trigger",
        "Water",
        "Weapon",
    ],
    "oracle-arcane-backlash-result": [
        "You affect or damage your surroundings, causing a disturbance or potential harm.",
        "You alert someone or something to your presence.",
        "You are lost in shadow, and find yourself in another place without memory of how you got there.",
        "You are not yourself, and act against a friend, ally, or companion.",
        "You are sapped of strength.",
        "You are tempted by dark powers.",
        "You are tormented by an apparition from your past.",
        "You are wracked with sudden sickness.",
        "You can’t perform this spell again until you acquire an important component.",
        "You collapse, and drift into a troubled sleep.",
        "You destroy an important object.",
        "You develop a strange fear or compulsion.",
        "You hear ghostly voices whispering of dark portents.",
        "You inadvertently summon a horror.",
        "You lose your connection to magic for a day or so, and cannot perform spells.",
        "You see a troubling vision of your future.",
        "You suffer the loss of a sense for several hours.",
        "You undergo a physical torment which leaves its mark upon you.",
        "You waste resources.",
        "Your friend, ally, or companion is adversely affected.",
        "Your spell affects the target in an unexpected and problematic way.",
        "Your spell causes creatures to exhibit strange or aggressive behavior.",
        "Your spell has the opposite effect.",
        "Your spell reveals a surprising and troubling truth.",
    ],
    "oracle-faction-name-result": {
        "template": [
            "{legacy} {affiliation}",
            "{legacy} {identity}",
            "{identity} of the {legacy} {affiliation}",
            "{affiliation} of the {legacy} {identity}",
        ],
        "tables":  {
            "legacy": [
                "Ancient",
                "Ashen",
                "Awakened",
                "Azure",
                "Blessed",
                "Bloody",
                "Broken",
                "Ceaseless",
                "Crimson",
                "Cursed",
                "Dawning",
                "Dissident",
                "Ebon",
                "Elder",
                "Enduring",
                "Enlightened",
                "Exalted",
                "Fallen",
                "Fated",
                "First",
                "Forgotten",
                "Forsaken",
                "Gloaming",
                "Golden",
                "Hidden",
                "Infernal",
                "Infinite",
                "Iron",
                "Kindred",
                "Obsidian",
                "Radiant",
                "Risen",
                "Sacred",
                "Sapphire",
                "Scarlet",
                "Serene",
                "Shattered",
                "Shining",
                "Silent",
                "Silver",
                "Sovereign",
                "Sundered",
                "Supreme",
                "Undying",
                "Unified",
                "United",
                "Universal",
                "Veiled",
                "Wandering",
            ],
            "identity": [
                "Army",
                "Blades",
                "Builders",
                "Daggers",
                "Defenders",
                "Disciples",
                "Domains",
                "Drifters",
                "Embers",
                "Flames",
                "Guardians",
                "Hammers",
                "Harbingers",
                "Heralds",
                "Hounds",
                "Hunters",
                "Jackals",
                "Keepers",
                "Knights",
                "Menders",
                "Outcasts",
                "Phantoms",
                "Raiders",
                "Ravens",
                "Reavers",
                "Relics",
                "Seekers",
                "Sentinels",
                "Serpents",
                "Servants",
                "Shadows",
                "Shards",
                "Skulls",
                "Souls",
                "Specters",
                "Swarm",
                "Swords",
                "Talons",
                "Vanguards",
                "Wardens",
                "Watchers",
                "Wolves",
                "Wraiths",
                "Wreckers",
                "Wrights",
            ],
            "affiliation": [
                "Accord",
                "Alliance",
                "Ascendancy",
                "Band",
                "Brotherhood",
                "Circle",
                "Clan",
                "Coalition",
                "Collective",
                "Commonwealth",
                "Consortium",
                "Council",
                "Court",
                "Covenant",
                "Cult",
                "Dominion",
                "Empire",
                "Followers",
                "Guardians",
                "Hand",
                "Imperium",
                "Knights",
                "League",
                "Legion",
                "Order",
                "Pact",
                "Regiment",
                "Republic",
                "Sphere",
                "Syndicate",
                "Union",
            ],
        },
    },
    "oracle-faction-type-result": [
        "<a href=\"/oracles/misc-oracles#faction-dominion\">Dominion</a> (Governing power)",
        "<a href=\"/oracles/misc-oracles#faction-guild\">Guild</a> (Organization of specialists)",
        "<a href=\"/oracles/misc-oracles#faction-fringe-group\">Fringe Group</a> (Band of outlaws, outcasts, or rogues)",
    ],
    "oracle-faction-influence-result": [
        "Forsaken: Banished or forgotten",
        "Isolated: Limited influence in a remote location",
        "Localized: Marginal influence in a single region",
        "Established: Strong influence in a single region",
        "Notable: Dispersed influence across a few regions",
        "Dominant: Far-reaching influence across many regions",
        "Inescapable: Pervasive influence across the known world",
    ],
    "oracle-faction-dominion-type-result": [
        "Agriculture",
        "Artistry",
        "Commerce",
        "Conquest",
        "Construction",
        "Diplomacy",
        "Education",
        "Environmentalism",
        "Exploration",
        "Faith",
        "History",
        "Honor",
        "Industry",
        "Isolationism",
        "Law",
        "Mysticism",
        "Pacifism",
        "Prophecy",
        "Secrecy",
        "Technology",
        "Treachery",
        "Warfare",
        "Wealth",
    ],
    "oracle-faction-dominion-leadership-result": [
        "Anarchist",
        "Fated or prophesied leader",
        "Disputed leadership",
        "Clan chiefs or elders",
        "Authoritarian dictatorship",
        "Elected representatives",
        "Oligarchical elite",
        "Dynastic lineage",
        "Varied / decentralized",
    ],
    "oracle-faction-guild-type-result": [
        "Assassins",
        "Bounty Hunters",
        "Couriers",
        "Courtesans",
        "Engineers",
        "Healers",
        "Industrialists",
        "Mercenaries",
        "Merchants",
        "Mystics",
        "Navigators",
        "Peacekeepers",
        "Researchers",
        "Spies",
    ],
    "oracle-faction-fringe-type-result": [
        "Cultists",
        "Exiles",
        "Gangsters",
        "Monster hunters",
        "Pirates",
        "Raiders",
        "Rebels",
        "Scavengers",
        "Smugglers",
        "Thieves",
    ],
    "oracle-faction-project-result": [
        "Broaden scope of the faction to include a new focus",
        "Build or secure a powerful device",
        "Consolidate control of a valuable commodity",
        "Destroy or defeat a rival",
        "Disrupt the operations of a rival",
        "Escape the control of another faction or power",
        "Establish a monument or memorial",
        "Establish a safe refuge or headquarters",
        "Expand operations to a new location or region",
        "Form an alliance",
        "Fulfill a prophecy",
        "Give aid to a faction",
        "Harness unnatural or forbidden power",
        "Hunt down a rogue asset",
        "Incite conflict among rivals",
        "Negotiate an agreement",
        "Obtain a needed commodity",
        "Obtain an important cultural artifact",
        "Obtain crucial data or information",
        "Obtain incriminating information about a rival",
        "Prevent a prophecy",
        "Put down an internal revolt or rebellion",
        "Repay a debt",
        "Rescue or recover a group or asset",
        "Research an innovation",
        "Resolve a conflict with another faction",
        "Reunite splintered elements of the faction",
        "Seize a powerful artifact or valuable treasure",
        "Seize rival territory or operations",
        "Subsume another faction",
        "Transport a valued asset",
        "Usurp leadership within a rival faction",
    ],
    "oracle-faction-quirks-result": [
        "Ancient or coded language",
        "Animal or creature motif used as a faction symbol",
        "Banishes the disloyal",
        "Body ornamentations signify castes or roles",
        "Conceals individual identity",
        "Dependent on an addictive substance",
        "Distinctive or elaborate clothing",
        "Elite soldiers provide defense or serve as bodyguards",
        "Favors a signature weapon",
        "Guided by superstition or prophecy",
        "Heavily stratified social structure",
        "Hoards ancient artifacts",
        "Honors the fallen through unusual death rites",
        "Idolizes a long-dead founder or martyr",
        "Keeps exhaustive records or archives",
        "Members take a new name when joining the faction",
        "Nomadic people and mobile operations",
        "Operates under strict codes or laws",
        "Recognizes others through a distinctive greeting or gesture",
        "Resolves disputes through formal duels",
        "Rites of adulthood or ascension",
        "Suspicious of outsiders",
        "Symbiotic relationship with a specific type of creature",
        "Trades in a unique currency or commodity",
        "Trains in a demanding physical discipline or martial art",
        "Wields unnatural abilities or strange arcane technologies",
        "Work or environment causes mutations",
    ],
    "oracle-faction-rumors-result": [
        "Hit hard by a recent attack or calamity",
        "Hoarding a valuable commodity",
        "Holds a powerful artifact",
        "Holds incriminating information against a leader or faction",
        "Infiltrated by a rival faction",
        "Knows the location of a fabled treasure or lost artifact",
        "Leaders are haunted by a dark prophecy",
        "Leaders are incompetent",
        "Leaders are puppets of another power or faction",
        "Lesser members of the leadership are plotting a coup",
        "New belief or religion is creating a schism among members",
        "Operations are a false front for their true purpose",
        "Plagued by infighting and low morale",
        "Plotting to betray an allied faction",
        "Preparing a major offensive or operation",
        "Pulling the strings of a leader or faction",
        "Recently acquired an unexpected fortune",
        "Secretly supporting a reviled faction",
        "Sheltering an infamous or dangerous fugitive",
        "Suffered destructive sabotage from within",
        "Suffering a shortage of key workers or personnel",
        "Uprising or revolt is brewing from within",
        "Vulnerable to attack or aggression",
    ],
};

export default miscOracleResults;