const monsterOracleResults = {
  "oracle-monstrosity-type-result": [
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Eldritch</a>.<br/> This monster has an interdimensional or extraterrestrial origin that defies logic and nature.",
    "<a>Fey</a>.<br/> This creature belongs to the otherworldly court of the Fae, and its intentions are duplicitous.",
  ],
  "oracle-monstrosity-size-result": [
    "Tiny (rodent-sized)", "Tiny (rodent-sized)",
    "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)",
    "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)",
    "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)",
    "Huge (whale-sized)", "Huge (whale-sized)", "Huge (whale-sized)",
    "Giant (tower-sized)", "Giant (tower-sized)",
    "Titanic (mountain-sized)",
  ],
  "oracle-monstrosity-form-result": [
    "Amorphous",
    "Amphibian",
    "Beast / mammal",
    "Bird",
    "Crustacean",
    "Elemental",
    "Fish",
    "Humanoid",
    "Incorporeal",
    "Insect",
    "Lizard",
    "Mineral",
    "Octopoid",
    "Plant",
    "Reptile",
    "Snake",
    "Spider",
    "Worm / slug",
  ],
  "oracle-monstrosity-characteristics-result": [
    "Antennae / sensory organs",
    "Bony protuberances",
    "Claws / talons",
    "Corrupted flesh",
    "Distinctive sound",
    "Egg sac / carried offspring",
    "Etched with mystic runes",
    "Exoskeleton / shell",
    "Extra limbs",
    "Fangs / rows of sharp teeth",
    "Horns / tusks",
    "Luminescent",
    "Mandibles / pincers",
    "Many-eyed",
    "Multi-headed",
    "Multi-segmented body",
    "Mummified / desiccated",
    "Oversized mouth",
    "Proboscis / inner jaw",
    "Rotting / skeletal",
    "Scarred / injured",
    "Semi-transparent",
    "Spikes / spines",
    "Stinger / barbs",
    "Strange color / markings",
    "Tail",
    "Tentacles / tendrils",
    "Wings",
  ],
  "oracle-monstrosity-abilities-result": [
    "Acidic",
    "Armored",
    "Breath weapon / toxic spew",
    "Burrower",
    "Camouflaged",
    "Climber",
    "Control elements",
    "Control lesser creatures",
    "Create illusions",
    "Crusher / constrictor",
    "Echolocation",
    "Electric shock",
    "Casts spells",
    "Feels no pain",
    "Flier / glider",
    "Grappler / entangler",
    "Horrid visage",
    "Immune to metals",
    "Intelligent",
    "Intimidating vocalization",
    "Keen senses",
    "Leaper",
    "Mimicry",
    "Mind control / telepathy",
    "Move between realities",
    "Noxious smell",
    "Paralyzing",
    "Parasitic",
    "Poisonous",
    "Powerful bite",
    "Semiaquatic / swimmer",
    "Shapeshifting",
    "Shoot projectiles",
    "Stealthy / ambusher",
    "Strong",
    "Swift",
    "Symbiotic",
    "Trap-setter",
    "Vibration sense",
    "Wield weapons",
    "Resistant to magic",
  ],
};
export default monsterOracleResults;