const monsterOracleResults = {
  "oracle-monstrosity-type-result": [
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Beast</a>.<br/> This monster is a twisted or corrupt version of an animal or critter.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Cursed</a>.<br/> This monster has been cursed with a vampiric, shapeshifting or similar supernatural malediction.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Undead</a>.<br/> This monster was once a living creature, its rotten corpse now reanimated by dark magic.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Demon</a>.<br/> This monster was spawned from pure corruption or emerged from the depths of hell.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Spectral</a>.<br/> This phantasmal entity traverses the veil between realities.",
    "<a>Eldritch</a>.<br/> This monster has an interdimensional or extraterrestrial origin that defies logic and nature.",
    "<a>Fey</a>.<br/> This creature belongs to the otherworldly court of the Fae, and its intentions are duplicitous.",
  ],
  "oracle-monstrosity-size-result": [
    "Tiny (rodent-sized)", "Tiny (rodent-sized)",
    "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)", "Small (hound-sized)",
    "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)", "Medium (person-sized)",
    "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)", "Large (wagon-sized)",
    "Huge (whale-sized)", "Huge (whale-sized)", "Huge (whale-sized)",
    "Giant (tower-sized)", "Giant (tower-sized)",
    "Titanic (mountain-sized)",
  ],
  "oracle-monstrosity-form-result": [
    "Amorphous",
    "Amphibian",
    "Beast / mammal",
    "Bird",
    "Crustacean",
    "Elemental",
    "Fish",
    "Humanoid",
    "Incorporeal",
    "Insect",
    "Lizard",
    "Mineral",
    "Octopoid",
    "Plant",
    "Reptile",
    "Snake",
    "Spider",
    "Worm / slug",
  ],
  "oracle-monstrosity-characteristics-result": [
    "Antennae / sensory organs",
    "Bony protuberances",
    "Claws / talons",
    "Corrupted flesh",
    "Distinctive sound",
    "Egg sac / carried offspring",
    "Etched with mystic runes",
    "Exoskeleton / shell",
    "Extra limbs",
    "Fangs / rows of sharp teeth",
    "Horns / tusks",
    "Luminescent",
    "Mandibles / pincers",
    "Many-eyed",
    "Multi-headed",
    "Multi-segmented body",
    "Mummified / desiccated",
    "Oversized mouth",
    "Proboscis / inner jaw",
    "Rotting / skeletal",
    "Scarred / injured",
    "Semi-transparent",
    "Spikes / spines",
    "Stinger / barbs",
    "Strange color / markings",
    "Tail",
    "Tentacles / tendrils",
    "Wings",
  ],
  "oracle-monstrosity-abilities-result": [
    "Acidic",
    "Armored",
    "Breath weapon / toxic spew",
    "Burrower",
    "Camouflaged",
    "Climber",
    "Control elements",
    "Control lesser creatures",
    "Create illusions",
    "Crusher / constrictor",
    "Echolocation",
    "Electric shock",
    "Casts spells",
    "Feels no pain",
    "Flier / glider",
    "Grappler / entangler",
    "Horrid visage",
    "Immune to metals",
    "Intelligent",
    "Intimidating vocalization",
    "Keen senses",
    "Leaper",
    "Mimicry",
    "Mind control / telepathy",
    "Move between realities",
    "Noxious smell",
    "Paralyzing",
    "Parasitic",
    "Poisonous",
    "Powerful bite",
    "Semiaquatic / swimmer",
    "Shapeshifting",
    "Shoot projectiles",
    "Stealthy / ambusher",
    "Strong",
    "Swift",
    "Symbiotic",
    "Trap-setter",
    "Vibration sense",
    "Wield weapons",
    "Resistant to magic",
  ],
  "oracle-demon-lord-title-result": {
    "template": [
      "{name}, {position} of {subject}",
      "{name}, the {position} of {subject}",
      "{name}, the {adjective} {position}",
      "{adjective} {position} {name}",
      "{position} {name}",
    ],
    "tables": {
      "name": [
        "Abaddon",
        "Adramalech",
        "Amon",
        "Apollyon",
        "Asmodeus",
        "Astaroth",
        "Azazel",
        "Baalberith",
        "Balaam",
        "Bast",
        "Behemoth",
        "Beherit",
        "Chemosh",
        "Dagyon",
        "Dambal",
        "Demogor",
        "Diabolos",
        "Gorth",
        "Haborym",
        "Ishtar",
        "Lilith",
        "Maimon",
        "Mantus",
        "Mardhal",
        "Marduk",
        "Melek",
        "Milmon",
        "Moloch",
        "Mormo",
        "Naamah",
        "Nergal",
        "Rimmon",
        "Sabazios",
        "Sammael",
        "Sedith",
        "Thoth",
      ],
      "adjective": [
        "Anguished",
        "Banished",
        "Colossal",
        "Corrupted",
        "Cursed",
        "Dark",
        "Demonic",
        "Deranged",
        "Diligent",
        "Disguised",
        "Eternal",
        "Euphoric",
        "Forsaken",
        "Gargantuan",
        "Golden",
        "Graceful",
        "Grave",
        "Great",
        "Grieving",
        "Heretical",
        "Hollow",
        "Hungry",
        "Juvenile",
        "Luminous",
        "Macabre",
        "Mad",
        "Marked",
        "Mute",
        "Nocturnal",
        "Rabid",
        "Radiant",
        "Righteous",
        "Tormented",
        "Venerable",
        "Voiceless",
        "Warped",
      ],
      "position": [
        "Apostle",
        "Baron",
        "Baroness",
        "Commander",
        "Consul",
        "Counselor",
        "Curator",
        "Delegate",
        "Divinity",
        "Exarch",
        "Guardian",
        "Herald",
        "High Priest",
        "Keeper",
        "King",
        "Liaison",
        "Lord",
        "Mad Priest",
        "Magi",
        "Master",
        "Matriarch",
        "Minister",
        "Missionary",
        "Mother",
        "Overlord",
        "Paladin",
        "Paragon",
        "Preacher",
        "Prince",
        "Princess",
        "Queen",
        "Sage",
        "Seer",
        "Tribune",
        "Warrior",
        "Witch",
      ],
      "subject": [
        "Ashes",
        "Beauty",
        "Birth",
        "Blood",
        "Brass",
        "Champions",
        "Chaos",
        "Cinders",
        "Cold",
        "Courage",
        "Crowns",
        "Darkness",
        "Death",
        "Fire",
        "Ghosts",
        "Harmony",
        "Hate",
        "Insanity",
        "Lies",
        "Nightmares",
        "Nights",
        "Poison",
        "Rot",
        "Servants",
        "Slaves",
        "Solitude",
        "Songs",
        "Sorrow",
        "Spirits",
        "Sunlight",
        "the End",
        "the Flock",
        "the Garden",
        "Victory",
        "Voices",
        "Wisdom",
      ],
    },
  },
  "oracle-demon-lord-aspect-result": [
    "Alchemist",
    "Ancestor / Old",
    "Artisan",
    "Bandit",
    "Collector",
    "Coward",
    "Crow / Raven",
    "Deserter",
    "Devout / Cultist",
    "Gravekeeper",
    "Heretic",
    "Hermit / Exile",
    "Hexer",
    "Hound / Hyena",
    "Inebriate / Glutton",
    "Inquisitor",
    "Jailer",
    "Juggernaut",
    "Lawkeeper",
    "Leech",
    "Lion / Tiger",
    "Loyalist",
    "Mystic / Saint",
    "Pawn",
    "Physician",
    "Rat / Lurker",
    "Serpent / Viper",
    "Silvertongue",
    "Spider",
    "Thrallmaster",
    "Tortoise",
    "Treasurer",
    "Trickster",
    "Twin / Triplet",
    "Warden / Protector",
    "Warlord",
  ],
  "oracle-demon-lord-asset-result": [
    "Barbarian clan",
    "Conspiracy",
    "Craft guild",
    "Crime family",
    "Dark cult",
    "Deadly prisoner",
    "Elite soldiers",
    "Explorers’ sect",
    "Family members",
    "Hollow guards",
    "Heist crew",
    "Heretical sect",
    "Hired killers",
    "Huge army",
    "Large food supply",
    "Local militia",
    "Many slaves",
    "Monstrous pet",
    "Noble house",
    "Persuasive",
    "Political party",
    "Religious party",
    "Renegade traitor",
    "Right hand",
    "Siege engines",
    "Skilled court",
    "Spy network",
    "State church",
    "Street gang",
    "Trade company",
    "Transformed men",
    "Valuables",
    "Vast wealth",
    "Worshippers",
  ],
};
export default monsterOracleResults;